Ads:
  description: Programma satur reklāmu
DisabledAlgorithm:
  description: Šai lietotnei ir vājš drošības paraksts
KnownVuln:
  description: Šī lietotne satur zināmu drošības ievainojamību
NoSourceSince:
  name: Avota kods vairs nav pieejams, nav iespējami atjauninājumi.
NonFreeAdd:
  description: Šī lietotne atbalsta ne-brīvus paplašinājumus
NonFreeAssets:
  description: Šī lietotne satur ne-brīvas sastāvdaļas
NonFreeDep:
  description: Šī lietotne ir atkarīga no citām ne-brīvām lietotnēm
NonFreeNet:
  description: Šī lietotne atbalsta ne-brīvus tīklus
Tracking:
  description: Šī programma seko jūsu aktivitātēm un ziņo par tām
UpstreamNonFree:
  description: Augšējā avota kods nav pilnībā brīvs
