Connectivity:
  name: Savienojamība
Development:
  name: Izstrādāšana
Games:
  name: Spēles
Graphics:
  name: Grafika
Internet:
  name: Internets
Money:
  name: Nauda
Multimedia:
  name: Multivides
Navigation:
  name: Navigācija
Phone & SMS:
  name: Tālrunis & īsziņa
Reading:
  name: Lasījumam
Science & Education:
  name: Zinātne un Izglītība
Security:
  name: Drošība
Sports & Health:
  name: Sports un veselība
System:
  name: Sistēmas
Theming:
  name: Motīvi
Time:
  name: Laiks
Writing:
  name: Rakstīšana
