Connectivity:
  name: Savienojamība
Development:
  name: Izstrāde
Games:
  name: Spēles
Graphics:
  name: Grafika
Internet:
  name: Internets
Money:
  name: Nauda
Multimedia:
  name: Multivide
Navigation:
  name: Kartes un pārvietošanās norādes
Phone & SMS:
  name: Tālrunis un īsziņas
Reading:
  name: Lasīšana
Science & Education:
  name: Zinātne un izglītība
Security:
  name: Drošība
Sports & Health:
  name: Sports un veselība
System:
  name: Sistēma
Theming:
  name: Izskats
Time:
  name: Laiks
Writing:
  name: Rakstīšana
