archive:
  description: بایگانی مخزن رسمی نرم‌افزار آزاد اف‌دروید. کاره‌های این‌جا قدیمیند و ممکن است دارای مشکلات امنیتی و آسیب‌پذیری‌های شناخته باشند!
  icon: fdroid-icon.png
  name: بایگانی اف‌دروید
repo:
  description: مخزن رسمی نرم‌افزار آزاد اف‌دروید. هرچیزی در این مخزن همواره از کد مبدأ ساخته می‌شود.
  icon: fdroid-icon.png
  name: اف‌دروید
