Ads:
  description: Deze app bevat advertenties
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Deze app heeft een zwakke beveiligingshandtekening
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Deze app bevat een bekende beveiligingskwetsbaarheid
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: De broncode is niet meer beschikbaar, updates zijn niet mogelijk.
NonFreeAdd:
  description: Deze app promoot niet-vrije add-ons
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Deze app bevat niet-vrije elementen
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Deze app vereist andere niet-vrije apps
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Deze app promoot niet-vrije netwerkdiensten
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Deze app houdt je activiteiten bij en rapporteert ze
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: De stroomopwaartse broncode is niet helemaal vrij
  icon: ic_antifeature_upstreamnonfree.png
