Ads:
  name: Publitzidade
  description: Custa aplicatzione cuntènnidi publitzidade
DisabledAlgorithm:
  name: Firmadu impreende un\'algoritmu non seguru
  description: Custa aplicatzione tenet una firma de seguresa dèbile
KnownVuln:
  name: Vulnerabilidade connota
  description: Custa aplicatzione tenet una vulnerabilidade de seguresa connota
NSFW:
  name: NSFW
  description: Custa aplicatzione tenet cuntenutos chi non si diant dèpere publitzizare
    o fàghere in manera chi siant visìbiles in neddue
NoSourceSince:
  name: Su còdighe mitza no est prus disponìbile, no est possìbile fàghere agiornamentos.
NonFreeAdd:
  name: Estensiones non lìberas
  description: Custa aplicatzione promovet estensiones (add-ons) non lìberas
NonFreeAssets:
  name: Cumponentes non lìberos
  description: Custa aplicatzione cuntennit cantos non lìberos
NonFreeDep:
  name: Dipendèntzias non lìberas
  description: Custa aplicatzione dipendet dae àteros aplicos non lìberos
NonFreeNet:
  name: Servìtzios de retza non lìberos
  description: Custa aplicatzione promovet servìtzios de retza non lìberos
Tracking:
  name: Arrastamentu
  description: Custa aplicatzione compidat e riferit a àteros de sas atividades tuas
UpstreamNonFree:
  name: A monte (upstream) non lìberu
  description: Su còdighe mitza originale no est lìberu de su totu
