Ads:
  name: Anuncios
  description: Esta aplicación tiene publicidad
DisabledAlgorithm:
  name: Firmado usando un algoritmo no seguro
  description: Esta aplicación tiene una firma de seguridad débil
KnownVuln:
  name: Vulnerabilidad conocida
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
NSFW:
  name: NSFW
  description: Esta app contiene contenido que no debería ser publicitado o visible
    en cualquier lugar
NoSourceSince:
  name: El código fuente ya no está disponible, no se puede actualizar.
NonFreeAdd:
  name: Complementos no libres
  description: Esta aplicación promueve complementos no libres
NonFreeAssets:
  name: Activos no libres
  description: Esta aplicación contiene recursos que no son libres
NonFreeDep:
  name: Dependencias no libres
  description: Esta aplicación depende de otras no libres
NonFreeNet:
  name: Servicios de red no libres
  description: Esta aplicación promueve servicios de red no libres
Tracking:
  name: Rastreo
  description: Esta aplicación rastrea e informa de su actividad
UpstreamNonFree:
  name: Original no libre
  description: El código fuente original no es totalmente libre
