Connectivity:
  name: Conectividad
Development:
  name: Desarrollo
Games:
  name: Juegos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Dinero
Multimedia:
  name: Multimedia
Navigation:
  name: Navegación
Phone & SMS:
  name: Teléfono y SMS
Reading:
  name: Lectura
Science & Education:
  name: Ciencia y educación
Security:
  name: Seguridad
Sports & Health:
  name: Deportes y salud
System:
  name: Sistema
Theming:
  name: Personalización del tema
Time:
  name: Hora, gestión del tiempo
Writing:
  name: Escritura
