archive:
  description: El archivo del repositorio oficial de Software Libre F-Droid. ¡Las aplicaciones son antiguas y pueden contener vulnerabilidades y problemas de seguridad conocidos!
  name: Archivo de F-Droid
repo:
  description: El repositorio oficial de software libre de F-Droid. Todo lo que hay en este repositorio siempre se construye a partir del código fuente.
  name: F-Droid
