Ads:
  description: Appen inneheld reklame
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Appen har ein svak tryggleikssignatur
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Appen inneheld eit kjent tryggleikshòl
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Kjeldekoden er ikkje lenger tilgjengeleg, så det er ikkje mogleg med oppdatering.
NonFreeAdd:
  description: Appen marknadsfører ufrie tillegg
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Appen inneheld ufrie ressursar
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Appen er avhengig av andre ufrie appar
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Appen marknadsfører ufrie nett-tenester
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Denne appen sporar og rapporterer aktiviteten din
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Kjeldekoden til oppstraums­appen er ikkje heilt fri
  icon: ic_antifeature_upstreamnonfree.png
