Ads:
  name: Annonser
  description: Denna app innehåller reklam
DisabledAlgorithm:
  name: Signerad med en osäker algoritm
  description: Denna app har en svag säkerhetssignatur
KnownVuln:
  name: Känd sårbarhet
  description: Denna app innehåller en känd säkerhetssårbarhet
NSFW:
  name: NSFW
  description: Denna app har ett innehåll som inte bör publiceras eller vara synligt
    var som helst
NoSourceSince:
  name: Källkoden är inte längre tillgänglig, inga uppdateringar möjliga.
NonFreeAdd:
  name: Icke-fria tillägg
  description: Denna app uppmuntrar icke-fria tillägg
NonFreeAssets:
  name: Icke-fria tillgångar
  description: Denna app innehåller icke-fria tillgångar
NonFreeDep:
  name: Icke-fria beroenden
  description: Denna app är beroende av andra icke-fria appar
NonFreeNet:
  name: Icke-fria nätverkstjänster
  description: Denna app uppmuntrar icke-fria nätverkstjänster
Tracking:
  name: Spårning
  description: Denna app spårar och rapporterar om din aktivitet
UpstreamNonFree:
  name: Icke-fri uppströms
  description: Källkoden från uppström är inte fullständigt fri
