Connectivity:
  name: Anslutbarhet
Development:
  name: Utveckling
Games:
  name: Spel
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Pengar
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: L채sning
Science & Education:
  name: Vetenskap & Utbildning
Security:
  name: S채kerhet
Sports & Health:
  name: Sport & H채lsa
System:
  name: System
Theming:
  name: Temas채ttning
Time:
  name: Tid
Writing:
  name: Skrivande
