Connectivity:
  name: Anslutbarhet
Development:
  name: Utveckling
Games:
  name: Spel
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Pengar
Multimedia:
  name: Multimedia
Navigation:
  name: Navigering
Phone_SMS:
  name: Telefon & SMS
Reading:
  name: L채sning
Science_Education:
  name: Vetenskap & utbildning
Security:
  name: S채kerhet
Sports_Health:
  name: Sport & h채lsa
System:
  name: System
Theming:
  name: Temas채ttning
Time:
  name: Tid
Writing:
  name: Skrivande
