Connectivity:
  name: Conectivitate
Development:
  name: Dezvoltare programe
Games:
  name: Jocuri
Graphics:
  name: Grafică
Internet:
  name: Internet
Money:
  name: Finanțe
Multimedia:
  name: Multimedia
Navigation:
  name: Navigație
Phone_SMS:
  name: Telefon & SMS
Reading:
  name: Citit
Science_Education:
  name: Știință & educație
Security:
  name: Securitate
Sports_Health:
  name: Sport & sănătate
System:
  name: Sistem
Theming:
  name: Teme
Time:
  name: Timp
Writing:
  name: Scris
