Ads:
  name: Anuncios
  description: Esta aplicación contén publicidade
DisabledAlgorithm:
  name: Asinado usando un algoritmo inseguro
  description: Esta aplicación ten unha sinatura de seguranza feble
KnownVuln:
  name: Vulnerabilidade Coñecida
  description: Esta aplicación contén unha vulnerabilidade de seguranza coñecida
NSFW:
  name: NSFW
  description: Esta aplicación contén contido que non debe ser divulgado ou visíbel
    en todos os lugares
NoSourceSince:
  name: O código fonte xá non está dispoñíbel e non é posíbel a súa actualización.
NonFreeAdd:
  name: Complementos non libres
  description: Esta aplicación promociona engadidos que non son libres ou de balde
NonFreeAssets:
  name: Activos non libres
  description: Esta aplicación contén elemento non libres
NonFreeDep:
  name: Dependencias non libres
  description: Esta aplicación depende doutras aplicacións non libres
NonFreeNet:
  name: Servizos de rede non libres
  description: Esta aplicación promove servizos de rede que non son libres
Tracking:
  name: Seguimento
  description: Esta aplicación rexistra e informa da túa actividade
UpstreamNonFree:
  name: Código fonte non libre
  description: O código fonte non é completamente libre
