Science & Education:
  name: زانست و فێرکردن
Writing:
  name: نووسین
Money:
  name: پارە
Security:
  name: پاراستن
Games:
  name: یاری
Navigation:
  name: ڕێدۆز
System:
  name: سیستەم
Connectivity:
  name: پەیوەندی
Development:
  name: گەشەپێدان
Phone & SMS:
  name: تەلەفۆن و کورتەنامە
Graphics:
  name: نیگارەیی
Internet:
  name: ئینتەرنێت
Theming:
  name: وتار
Reading:
  name: خوێندنەوە
Sports & Health:
  name: تەندرووستی و وەرزش
Multimedia:
  name: ڕەنگاڵە
Time:
  name: کات
