Connectivity:
  name: Conectividad
Development:
  name: Desarrollo
Games:
  name: Juegos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Dinero
Multimedia:
  name: Multimedia
Navigation:
  name: Navegación
Phone_SMS:
  name: Teléfono y SMS
Reading:
  name: Lectura
Science_Education:
  name: Ciencias y Educación
Security:
  name: Seguridad
Sports_Health:
  name: Deportes y Salud
System:
  name: Sistema
Theming:
  name: Personalización
Time:
  name: Tiempo
Writing:
  name: Escritura
