Categories:
  - Science & Education
License: GPL-3.0-or-later
SourceCode: https://gitlab.com/bencyric/cs-137-app-cyric
IssueTracker: https://gitlab.com/bencyric/cs-137-app-cyric/issues

AutoName: Cs-137 App by CYRIC

RepoType: git
Repo: https://gitlab.com/bencyric/cs-137-app-cyric.git
Binaries: https://gitlab.com/bencyric/cs-137-app-cyric/uploads/933203848c7b54fbc93c068772bd454d/cs-137-app.apk

Builds:
  - versionName: '1.0'
    versionCode: 1
    commit: 289afd4d97258a0962ab3a5ab5d393dbfb473ad3
    subdir: app
    gradle:
      - yes

AllowedAPKSigningKeys: 0ada4d6506734ab98912825d89ee5a51a2ffb8b49e0a52ae5871db0e876ee435

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '1.0'
CurrentVersionCode: 1
