Categories:
  - Multimedia
License: Apache-2.0
SourceCode: https://github.com/zoff99/libavif-android
IssueTracker: https://github.com/zoff99/libavif-android/issues

AutoName: AVIF Viewer
Summary: AVIF Image Viewer
Description: |-
    This app is a simple AVIF Imageviewer for Android.
    Before Android 12 it is not easy to view AVIF Images.

RepoType: git
Repo: https://github.com/zoff99/libavif-android

Builds:
  - versionName: 1.0.2
    versionCode: 10002
    commit: 92764383bab70b6133b5b0a3ca114da4b309ad45
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version %v
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.2
CurrentVersionCode: 10002
