Categories:
  - Multimedia
  - System
License: Apache-2.0
AuthorName: Simon Marquis
AuthorEmail: contact@simon-marquis.fr
AuthorWebSite: https://simon-marquis.fr/
SourceCode: https://github.com/SimonMarquis/Android-SoundQuickSettings
IssueTracker: https://github.com/SimonMarquis/Android-SoundQuickSettings/issues
Changelog: https://github.com/SimonMarquis/Android-SoundQuickSettings/releases

AutoName: Sound Quick Settings

RepoType: git
Repo: https://github.com/SimonMarquis/Android-SoundQuickSettings.git

Builds:
  - versionName: 1.0.5
    versionCode: 10500
    commit: 38f85680e5821e27b5be2a3ad943565666447563
    subdir: app
    gradle:
      - yes

MaintainerNotes: AUM disabled due to generated version code

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 1.0.5
CurrentVersionCode: 10500
