AntiFeatures:
  - NonFreeNet
Categories:
  - Reading
License: GPL-3.0-or-later
AuthorName: Cooaer
AuthorEmail: v2compose@gmail.com
SourceCode: https://github.com/cooaer/v2compose
IssueTracker: https://github.com/cooaer/v2compose/issues
Changelog: https://github.com/cooaer/v2compose/releases

AutoName: V2compose

RepoType: git
Repo: https://github.com/cooaer/v2compose.git
Binaries: https://github.com/cooaer/v2compose/releases/download/v%v/v2compose-v%v-foss.apk

Builds:
  - versionName: 1.0.0
    versionCode: 100
    commit: e7106535afdb5d64e8a6fe17615c5a4040828381
    subdir: app
    gradle:
      - foss
    prebuild: sed -i -e '/gms/d' -e '/firebase/d' {..,.}/build.gradle

  - versionName: 1.0.1
    versionCode: 101
    commit: 3832a534437f14c955f9fc46902a6501bca8b194
    subdir: app
    gradle:
      - foss
    prebuild: sed -i -e '/gms/d' -e '/firebase/d' {..,.}/build.gradle

AllowedAPKSigningKeys: f8ad4fc3d08e077a990d66634ab6f63fd2d79114e3d785ebd307265cec0edac0

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.0.1
CurrentVersionCode: 101
