Categories:
  - Multimedia
  - Writing
License: LGPL-2.1-only
WebSite: http://tuxguitar.com.ar/
SourceCode: https://sourceforge.net/p/tuxguitar/code/
IssueTracker: https://sourceforge.net/p/tuxguitar/bugs/
Donate: http://tuxguitar.com.ar/donate.html

Summary: TuxGuitar is a multitrack tablature editor and player
Description: |-
    TuxGuitar is a multitrack tablature editor and player.
    It can open Guitar Pro and PowerTab files.

    With TuxGuitar, you will be able to compose music using
    the following features:

    * Tablature editor
    * Score Viewer
    * Autoscroll while playing
    * Note duration management
    * Various effects (bend, slide, vibrato, hammer-on/pull-off)
    * Support for triplets (5,6,7,9,10,11,12)
    * Repeat open, close and alternative endings
    * Time signature management
    * Tempo management

RepoType: git
Repo: https://gitlab.com/f-droid-mirrors/empty.git

Builds:
  - versionName: SNAPSHOT
    versionCode: 1
    commit: d3746f98
    init: svn checkout -r 1821 svn://svn.code.sf.net/p/tuxguitar/code/trunk/ .
    patch:
      - remove_gdrive.patch
    output: build-scripts/tuxguitar-android/apk/build/outputs/apk/release/tuxguitar-android-SNAPSHOT-release-unsigned.apk
    srclibs:
      - mididriver@v1.20
    prebuild:
      - find . -iname "*.jar" -o -iname "*.zip" -o -iname "*.so" -exec rm {} \;
      - rm -rf TuxGuitar-android-gdrive
      - rm -rf TuxGuitar-android-gdrive-gdaa
      - rm -rf TuxGuitar-android-gdrive-plugin
      - sed -i -e "s/^\s*versionCode.*/        versionCode $$VERCODE$$/" build-scripts/tuxguitar-android/apk/build.gradle
    scanignore:
      - TuxGuitar-android/src/org/herac/tuxguitar/android/resource/TGResourceLoaderImpl.java
    scandelete:
      - .
    build:
      - export BUILD_DIR=$(pwd)
      - cd $$mididriver$$
      - gradle assembleRelease
      - cd build/intermediates/merged_native_libs/release/out/lib
      - cp -r * ${BUILD_DIR}/TuxGuitar-android-midimaster/libs
      - cd ${BUILD_DIR}/build-scripts/tuxguitar-android/apk
      - gradle assembleRelease
    ndk: r21d

MaintainerNotes: |-
    Using a dummy repo because svn-type repos are deprecated
    And git-svn is incredibly slow.
    Upstream doesn't have tags or any way to determine the release
    versionCode is generated from build date, so we instead use our own

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: SNAPSHOT
CurrentVersionCode: 1
