image: mvdan/fdroid-ci:latest

before_script:
  - apt-get update && apt-get install -y python3 python3-yaml
  - rm -rf fdroidserver
  - git clone https://gitlab.com/fdroid/fdroidserver.git --depth=1
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py

lint:
  script:
    - fdroid lint -f
