image: registry.gitlab.com/fdroid/ci-images-server:latest

before_script:
  - rm -rf fdroidserver
  - git clone --depth=1 https://gitlab.com/fdroid/fdroidserver.git
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py

lint:
  script:
    - export EXITVALUE=0
    - fdroid lint -f || {
          export EXITVALUE=1;
          printf "\nThese files have lint issues:\n";
          fdroid rewritemeta -l;
          printf "\nThese are the formatting issues:\n";
          fdroid rewritemeta;
          git --no-pager diff --color=always;
      }
    - exit $EXITVALUE
