before_script:
  - apt-get update -qy
  - apt-get install -y python python-requests python-magic
  - test -d fdroidserver && rm -rf fdroidserver
  - git clone https://gitlab.com/fdroid/fdroidserver.git fdroidserver --depth=10
  - export PATH="$PATH:$PWD/fdroidserver"

metadata_check:
  script:
    - cd fdroiddata && fdroid readmeta
