#image: python:2.7

services:

before_script:
  - sudo apt-get update -qq
  #- sudo apt-get install -y libxml2-dev
  - wget 'https://gitlab.com/fdroid/fdroidserver/repository/archive.tar.bz2?ref=master' -O '/tmp/fdroidserver.tar.bz2'
  - tar -xvf '/tmp/fdroidserver.tar.bz2'
  - export PATH="$PATH:$PWD/fdroidserver.git/"

metadata_check:
  script:
    - fdroid readmeta
