image: mvdan/fdroid-ci:base-20160405

before_script:
  - rm -rf fdroidserver
  # TODO(mvdan): re-add --depth=1 once this is fixed:
  # https://gitlab.com/gitlab-com/support-forum/issues/652
  - git clone https://gitlab.com/fdroid/fdroidserver.git
  - export PATH="$PWD/fdroidserver:$PATH"
  - touch config.py

lint:
  script:
    - fdroid lint -f
