before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-setuptools
  - wget 'https://gitlab.com/fdroid/fdroidserver/repository/archive.tar.bz2?ref=master' -O '/tmp/fdroidserver.tar.bz2'
  - tar -xvf '/tmp/fdroidserver.tar.bz2'
  - python2 fdroidserver.git/setup.py install

metadata_check:
  script:
    - fdroid readmeta
