before_script:
  - apt-get update -qy
  - apt-get install -y python
  - git clone https://gitlab.com/fdroid/fdroidserver.git fdroidserver --depth=10
  - export PATH="$PATH:$PWD/fdroidserver"

metadata_check:
  script:
    - fdroid readmeta
