before_script:
  - apt-get update -qy
  - apt-get install -y python python-setuptools
  - git clone https://gitlab.com/fdroid/fdroidserver.git fdroidserver --depth=10
  - cd fdroidserver
  - python2 setup.py install

metadata_check:
  script:
    - fdroid readmeta
