Ads:
  name: Sanasachd
  description: Tha sanasachd am broinn na h-aplacaid seo
DisabledAlgorithm:
  name: Soidhneadh le algairim nach eil sàbhailte
  description: Tha soidhneadh tèarainteachd lag aig an aplacaid seo
KnownVuln:
  name: So-leòntachd aithnichte
  description: Tha so-leòntachd tèarainteachd aithnichte am broinn na h-aplacaid seo
NSFW:
  name: NSFW
  description: Tha susbaint san aplacaid seo nach bu chòir fhoillseachadh no a bhith
    ri fhaicinn air feadh an àite
NoSourceSince:
  name: Chan eil am bun-tùs ri fhaighinn tuilleadh is cha ghabh a h-ùrachadh.
NonFreeAdd:
  name: Tuilleadain neo-shaor
  description: Brosnaichidh an aplacaid seo tuilleadain nach eil saor
NonFreeAssets:
  name: Maoin neo-shaor
  description: Tha maoin nach eil saor am broinn na h-aplacaid seo
NonFreeDep:
  name: Eisimeileachdan neo-shaor
  description: Tha an aplacaid seo an eisimeil air aplacaidean eile nach eil saor
NonFreeNet:
  name: Seirbheisean lìonraidh neo-shaor
  description: Brosnaichidh an aplacaid seo seirbheisean lìonraidh nach eil saor
Tracking:
  name: Tracadh
  description: Nì an aplacaid seo tracadh ort is nì i aithris air do ghnìomhachd
UpstreamNonFree:
  name: Upstream neo-shaor
  description: Chan eil bun-tùs an upstream saor gu tur
