Connectivity:
  name: Comas-ceangail
Development:
  name: Leasachadh
Games:
  name: Geamannan
Graphics:
  name: Grafaigeachd
Internet:
  name: Eadar-lìon
Money:
  name: Airgead
Multimedia:
  name: Meadhanan
Navigation:
  name: Seòladaireachd
Phone_SMS:
  name: Fòn ⁊ SMS
Reading:
  name: Leughadh
Science_Education:
  name: Saidheans ⁊ foghlam
Security:
  name: Tèarainteachd
Sports_Health:
  name: Spòrs ⁊ slàinte
System:
  name: An siostam
Theming:
  name: Ùrlaran
Time:
  name: Àm
Writing:
  name: Sgrìobhadh
