Connectivity:
  name: Повезивање
Development:
  name: Развој
Games:
  name: Игре
Graphics:
  name: Графика
Internet:
  name: Интернет
Money:
  name: Новац
Multimedia:
  name: Мултимедија
Navigation:
  name: Навођење
Phone_SMS:
  name: Телефон и СМС
Reading:
  name: Читање
Science_Education:
  name: Наука и образовање
Security:
  name: Безбедност
Sports_Health:
  name: Спорт и здравље
System:
  name: Систем
Theming:
  name: Теме
Time:
  name: Време
Writing:
  name: Писање
