archive:
  description: Архива званичног F-Droid-овог репозиторијума слободног софтвера. Апликације у њему су застареле и могу да садрже познате рањивости и безбедносне проблеме!
  name: F-Droid архива
repo:
  description: Званични F-Droid-ов репозиторијум слободног софтвера. Све у њему се увек прикупља из изворног кода.
  name: F-Droid
