Ads:
  name: Reklama
  description: Ky aplikacion përmban reklama
DisabledAlgorithm:
  name: Nënshkruar Duke Përdorur Një Algoritëm Jo të Parrezik
  description: Ky aplikacion ka një nënshkrim të dobët sigurie
KnownVuln:
  name: Cenueshmëri e Ditur
  description: Ky aplikacion përmban një cenueshmëri të njohur sigurie
NSFW:
  name: NSFW
  description: Ky aplikacion përmban lëndë që s’duhet bërë publike apo të jetë e dukshme
    kudo
NoSourceSince:
  name: Kodi burim s’mund të kihet më, s’ka përditësime të mundshme.
NonFreeAdd:
  name: Shtesa Jo të Lira
  description: Ky aplikacion rekomandon shtesa jo të lira
NonFreeAssets:
  name: Elementë Jo të Lirë
  description: Ky aplikacion përmban elementë jo të lirë
NonFreeDep:
  name: Varësi Jo të Lira
  description: Ky aplikacion varet nga aplikacione të tjera jo të lira
NonFreeNet:
  name: Shërbime Rrjeti Jo të Lira
  description: Ky aplikacion rekomandon shërbime rrjeti jo të lira
Tracking:
  name: Gjurmim
  description: Ky aplikacion gjurmon dhe raporton veprimtarinë tuaj
UpstreamNonFree:
  name: “Upstream” Jo i Lirë
  description: Kodi burim origjinal s’është plotësisht i Lirë
