Connectivity:
  icon: category_connectivity.png
  name: Aftësi lidhjeje
Development:
  icon: category_development.png
  name: Zhvillim
Games:
  icon: category_games.png
  name: Lojëra
Graphics:
  icon: category_graphics.png
  name: Grafika
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Para
Multimedia:
  name: Multimedia
Navigation:
  icon: category_navigation.png
  name: Lëvizje
Phone & SMS:
  name: Telefon & SMS
Reading:
  icon: category_reading.png
  name: Lexim
Science & Education:
  icon: category_science_education.png
  name: Shkencë & Arsim
Security:
  icon: category_security.png
  name: Siguri
Sports & Health:
  name: Sporte & Shëndet
System:
  icon: category_system.png
  name: Sistem
Theming:
  icon: category_theming.png
  name: Ndryshim teme grafike
Time:
  name: Kohë
Writing:
  icon: category_writing.png
  name: Shkrim
