Connectivity:
  name: Aftësi lidhjeje
Development:
  name: Zhvillim
Games:
  name: Lojëra
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Para
Multimedia:
  name: Multimedia
Navigation:
  name: Lëvizje
Phone_SMS:
  name: Telefon & SMS
Reading:
  name: Lexim
Science_Education:
  name: Shkencë & Arsim
Security:
  name: Siguri
Sports_Health:
  name: Sporte & Shëndet
System:
  name: Sistem
Theming:
  name: Ndryshim teme grafike
Time:
  name: Kohë
Writing:
  name: Shkrim
