archive:
  description: Arkivi i depos zyrtare Software i Lirë F-Droid. Aplikacionet këtu janë të vjetër dhe mund të përmbajnë probleme të ditura cenueshmërie dhe sigurie!
  icon: fdroid-icon.png
  name: Arkiv F-Droid
repo:
  description: Depoja zyrtare Software i Lirë F-Droid. Gjithçka në këtë depo montohet përherë që nga kodi burim.
  icon: fdroid-icon.png
  name: F-Droid
