Ads:
  description: Ứng dụng này có quảng cáo
  icon: ic_antifeature_ads.png
  name: Quảng cáo
DisabledAlgorithm:
  description: Ứng dụng này có chữ kí bảo mật yếu
  icon: ic_antifeature_disabledalgorithm.png
  name: Được kí bằng thuật toán không an toàn
KnownVuln:
  description: Ứng dụng này có một lỗ hổng bảo mật đã biết
  icon: ic_antifeature_knownvuln.png
  name: Lỗ hổng bảo mật đã biết
NSFW:
  description: Ứng dụng này chứa nội dung không nên được công khai ở mọi nơi
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Mã nguồn không còn nữa, không thể có cập nhật.
NonFreeAdd:
  description: Ứng dụng này khuyến khích các phần mở rộng không tự do
  icon: ic_antifeature_nonfreeadd.png
  name: Phần mở rộng không tự do
NonFreeAssets:
  description: Ứng dụng này có những phần không tự do
  icon: ic_antifeature_nonfreeassets.png
  name: Các phần không tự do
NonFreeDep:
  description: Ứng dụng này phụ thuộc vào các ứng dụng không tự do khác
  icon: ic_antifeature_nonfreedep.png
  name: Phụ thuộc vào những thứ không tự do
NonFreeNet:
  description: Ứng dụng này khuyến khích các dịch vụ mạng không tự do
  icon: ic_antifeature_nonfreenet.png
  name: Dịch vụ mạng không tự do
Tracking:
  description: Ứng dụng này theo dõi và báo cáo hoạt động của bạn
  icon: ic_antifeature_tracking.png
  name: Theo dõi
UpstreamNonFree:
  description: Mã nguồn không hoàn toàn tự do
  icon: ic_antifeature_upstreamnonfree.png
  name: Dự án mẹ không tự do
