Ads:
  name: Quảng cáo
  description: Ứng dụng này có quảng cáo
DisabledAlgorithm:
  name: Được kí bằng thuật toán không an toàn
  description: Ứng dụng này có chữ kí bảo mật yếu
KnownVuln:
  name: Lỗ hổng bảo mật đã biết
  description: Ứng dụng này có một lỗ hổng bảo mật đã biết
NSFW:
  name: NSFW
  description: Ứng dụng này chứa nội dung không nên được công khai ở mọi nơi
NoSourceSince:
  name: Mã nguồn không còn nữa, không thể có cập nhật.
NonFreeAdd:
  name: Phần mở rộng không tự do
  description: Ứng dụng này khuyến khích các phần mở rộng không tự do
NonFreeAssets:
  name: Các phần không tự do
  description: Ứng dụng này có những phần không tự do
NonFreeDep:
  name: Phụ thuộc vào những thứ không tự do
  description: Ứng dụng này phụ thuộc vào các ứng dụng không tự do khác
NonFreeNet:
  name: Dịch vụ mạng không tự do
  description: Ứng dụng này khuyến khích các dịch vụ mạng không tự do
Tracking:
  name: Theo dõi
  description: Ứng dụng này theo dõi và báo cáo hoạt động của bạn
UpstreamNonFree:
  name: Dự án mẹ không tự do
  description: Mã nguồn không hoàn toàn tự do
