Ads:
  description: Este aplicativo contém anúncios
  icon: ic_antifeature_ads.png
  name: Anúncios
DisabledAlgorithm:
  description: Este aplicativo tem uma assinatura de segurança fraca
  icon: ic_antifeature_disabledalgorithm.png
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Este aplicativo contém uma falha de segurança já conhecida
  icon: ic_antifeature_knownvuln.png
  name: Vulnerabilidade conhecida
NSFW:
  description: Este aplicativo contém conteúdo impróprio para menores de idade
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Não é possível atualizar, o código fonte não está mais disponível.
NonFreeAdd:
  description: Este aplicativo promove complementos não livres
  icon: ic_antifeature_nonfreeadd.png
  name: Complementos não livres
NonFreeAssets:
  description: Este aplicativo contém conteúdo não livre
  icon: ic_antifeature_nonfreeassets.png
  name: Conteúdos não livres
NonFreeDep:
  description: Este aplicativo depende de aplicativos não livres
  icon: ic_antifeature_nonfreedep.png
  name: Dependências não livres
NonFreeNet:
  description: Este aplicativo promove ou depende inteiramente de um serviço de rede não mutável ou não gratuito
  icon: ic_antifeature_nonfreenet.png
  name: Serviços de rede não livres
Tracking:
  description: Este aplicativo rastreia e relata sua atividade
  icon: ic_antifeature_tracking.png
  name: Rastreamento
UpstreamNonFree:
  description: O código fonte original não é totalmente livre
  icon: ic_antifeature_upstreamnonfree.png
  name: Upstream não livre
TetheredNet:
  description: Este app promove ou depende inteiramente de uma determinada instância de um serviço de rede.
  name: Serviços de rede vinculada
