repo:
  description: Repositório oficial F-Droid Free Software. Tudo neste repositório é sempre construído a partir do código-fonte.
  name: F-Droid
archive:
  description: Repositório de arquivamento oficial F-Droid Free Software. Os aplicativos aqui são antigos e podem conter vulnerabilidades conhecidas e problemas de segurança!
  name: F-Droid Arquivamento
