Development:
  name: ⵜⵉⴳⵎⵉ
Games:
  name: ⵓⵔⴰⵔⵏ
Internet:
  name: ⴰⵏⵜⵉⵔⵏⵉⵜ
Money:
  name: ⴰⵥⵕⴼ
Reading:
  name: ⵜⵉⵖⵓⵔⵉ
Science_Education:
  name: ⵜⴰⵎⴰⵙⵙⴰⵏⵜ ⴷ ⵓⵙⴳⵎⵉ
Security:
  name: ⵙⵙⵍⴰⵎⵜ
Time:
  name: ⴰⴳⵓⵔ
Writing:
  name: ⵜⵉⵔⵔⴰ
