Ads:
  description: Hierdie program bevat advertensies
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Hierdie app het \'n swak sekuriteitshandtekening
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Hierdie inligting bevat \'n bekende veiligheidskwesbaarheid
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Die bronkode is nie meer beskikbaar nie, geen opdaterings moontlik nie.
NonFreeAdd:
  description: Hierdie program bevorder nie-vrye toevoegsels
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Hierdie program bevat nie-vrye bates
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Hierdie program is afhanklik van ander nie-vrye programme
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Hierdie program bevorder nie-vrye netwerk dienste
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Hierdie program speur op, en rapporteer jou aktiwiteite
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Die stroomop bronkode is nie heeltemal vry nie
  icon: ic_antifeature_upstreamnonfree.png
