Ads:
  description: اس ایپ میں اشتہارات شامل ہیں۔
  icon: ic_antifeature_ads.png
  name: اشتہارات
DisabledAlgorithm:
  description: اس ایپ میں سیکیورٹی کا کمزور دستخط ہے۔
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: اس ایپ میں سیکیورٹی کی ایک معلوم کمزوری ہے۔
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: سورس کوڈ اب دستیاب نہیں ہے ، کوئی اپ ڈیٹ ممکن نہیں ہے۔
NonFreeAdd:
  description: یہ ایپ غیر فری ایڈ کو فروغ دیتی ہے۔
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: یہ ایپ غیر مفت اثاثوں پر مشتمل ہے
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: یہ ایپ دیگر غیر مفت ایپس پر منحصر ہے
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: یہ ایپ غیر فری نیٹ ورک خدمات کو فروغ دیتی ہے۔
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: یہ ایپ آپ کی سرگرمیوں کو ٹریک اور رپورٹ کرتی ہے۔
  icon: ic_antifeature_tracking.png
  name: ٹریکنگ
UpstreamNonFree:
  description: اپ سٹریم سورس کوڈ مکمل طور پر مفت نہیں ہے
  icon: ic_antifeature_upstreamnonfree.png
