Ads:
  name: اشتہارات
  description: اس ایپ میں اشتہارات شامل ہیں۔
DisabledAlgorithm:
  description: اس ایپ میں سیکیورٹی کا کمزور دستخط ہے۔
KnownVuln:
  description: اس ایپ میں سیکیورٹی کی ایک معلوم کمزوری ہے۔
NoSourceSince:
  name: سورس کوڈ اب دستیاب نہیں ہے ، کوئی اپ ڈیٹ ممکن نہیں ہے۔
NonFreeAdd:
  description: یہ ایپ غیر فری ایڈ کو فروغ دیتی ہے۔
NonFreeAssets:
  description: یہ ایپ غیر مفت اثاثوں پر مشتمل ہے
NonFreeDep:
  description: یہ ایپ دیگر غیر مفت ایپس پر منحصر ہے
NonFreeNet:
  description: یہ ایپ غیر فری نیٹ ورک خدمات کو فروغ دیتی ہے۔
Tracking:
  name: ٹریکنگ
  description: یہ ایپ آپ کی سرگرمیوں کو ٹریک اور رپورٹ کرتی ہے۔
UpstreamNonFree:
  description: اپ سٹریم سورس کوڈ مکمل طور پر مفت نہیں ہے
