Connectivity:
  name: Ku
Development:
  name: Hormarka
Games:
  name: Geemamka
Graphics:
  name: Farshaxa
Internet:
  name: Khadka
Money:
  name: Lacag
Multimedia:
  name: Lagu
Navigation:
  name: Dhex
Phone & SMS:
  name: Taleefanka &
Reading:
  name: Akhriska
Science & Education:
  name: Sayniska & Waxbarashada
Security:
  name: Amniga
Sports & Health:
  name: Ciyaaraha & Caafimaadka
System:
  name: Aalada
Time:
  name: Wakhtiga
Writing:
  name: Qorista
