Ads:
  description: Ta aplikacija vsebuje oglaševanje
  icon: ic_antifeature_ads.png
  name: Oglasi
DisabledAlgorithm:
  description: Ta aplikacija ima šibek varnostni podpis
  icon: ic_antifeature_disabledalgorithm.png
  name: Podpisano z nezaščitenim algoritmom
KnownVuln:
  description: Ta aplikacija vsebuje znano varnostno pomanjkljivost
  icon: ic_antifeature_knownvuln.png
  name: Znana ranljivost
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Izvirna koda ni več na voljo, zato posodobitve niso možne.
NonFreeAdd:
  description: Ta aplikacija promovira plačljive dodatke
  icon: ic_antifeature_nonfreeadd.png
  name: Ne-prosti dodatki
NonFreeAssets:
  description: Ta aplikacija vsebuje neodprte enote
  icon: ic_antifeature_nonfreeassets.png
  name: Ne-prosta sredstva
NonFreeDep:
  description: Ta aplikcija je odvisna od ostalih ne odprtih aplikacijah
  icon: ic_antifeature_nonfreedep.png
  name: Ne-proste odvisnosti
NonFreeNet:
  description: Ta aplikacija promovira plačljive internetne storitve
  icon: ic_antifeature_nonfreenet.png
  name: Ne-prosti omrežne storitve
Tracking:
  description: Ta aplikacija vam sledi in poroča o vaši aktivnosti
  icon: ic_antifeature_tracking.png
  name: Sledenje
UpstreamNonFree:
  description: Originalna koda ni popolnoma odprta
  icon: ic_antifeature_upstreamnonfree.png
  name: Ne-prost Upstream
