Ads:
  name: Oglasi
  description: Ta aplikacija vsebuje oglaševanje
DisabledAlgorithm:
  name: Podpisano z nezaščitenim algoritmom
  description: Ta aplikacija ima šibek varnostni podpis
KnownVuln:
  name: Znana ranljivost
  description: Ta aplikacija vsebuje znano varnostno pomanjkljivost
NoSourceSince:
  name: Izvirna koda ni več na voljo, zato posodobitve niso možne.
NonFreeAdd:
  name: Ne-prosti dodatki
  description: Ta aplikacija promovira plačljive dodatke
NonFreeAssets:
  name: Ne-prosta sredstva
  description: Ta aplikacija vsebuje neodprte enote
NonFreeDep:
  name: Ne-proste odvisnosti
  description: Ta aplikcija je odvisna od ostalih ne odprtih aplikacijah
NonFreeNet:
  name: Ne-prosti omrežne storitve
  description: Ta aplikacija promovira plačljive internetne storitve
Tracking:
  name: Sledenje
  description: Ta aplikacija vam sledi in poroča o vaši aktivnosti
UpstreamNonFree:
  name: Ne-prost Upstream
  description: Originalna koda ni popolnoma odprta
