Connectivity:
  name: Povezljivost
Development:
  name: Razvijanje
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Denar
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone_SMS:
  name: Telefon & SMS
Reading:
  name: Branje
Science_Education:
  name: Znanost & Izobrazba
Security:
  name: Varnost
Sports_Health:
  name: Šport & zdravje
System:
  name: Sistem
Theming:
  name: Izgled
Time:
  name: Čas
Writing:
  name: Pisanje
