Ads:
  name: Mainokset
  description: Tämä sovellus sisältää mainoksia
DisabledAlgorithm:
  name: Allekirjoitettu turvattomalla algoritmilla
  description: Tällä sovelluksella on heikko turvallisuusallekirjoitus
KnownVuln:
  name: Tunnettu haavoittuvuus
  description: Tämä sovellus sisältää tunnetun haavoittuvuuden
NSFW:
  name: NSFW
  description: Sovelluksessa on sisältöä, jota ei tulisi julkaista tai näyttää kaikkialla
NoSourceSince:
  name: Lähdekoodi ei ole enää saatavilla, päivityksiä ei voi tehdä.
NonFreeAdd:
  name: Ei-vapaat lisäosat
  description: Tämä sovellus suosittelee ei-vapaita lisäosia
NonFreeAssets:
  name: Ei-vapaa sisältö
  description: Tämä sovellus sisältää ei-vapaita osia
NonFreeDep:
  name: Ei-vapaat riippuvuudet
  description: Tämä sovellus on riippuvainen muista, ei-vapaista sovelluksista
NonFreeNet:
  name: Ei-vapaat verkkopalvelut
  description: Tämä sovellus tukee ei-vapaita verkkopalveluja
Tracking:
  name: Seuranta
  description: Tämä sovellus tarkkailee ja raportoi toimintaasi
UpstreamNonFree:
  name: Upstream ei-vapaa
  description: Ylätason lähdekoodi ei ole kokonaan vapaata
