Connectivity:
  name: Yhteydet
Development:
  name: Kehittäminen
Games:
  name: Pelit
Graphics:
  name: Grafiikka
Internet:
  name: Internet
Money:
  name: Raha
Multimedia:
  name: Multimedia
Navigation:
  name: Navigointi
Phone & SMS:
  name: Puhelin & SMS
Reading:
  name: Lukeminen
Science & Education:
  name: Tiede & koulutus
Security:
  name: Tietoturva
Sports & Health:
  name: Urheilu & terveys
System:
  name: Järjestelmä
Theming:
  name: Teemat
Time:
  name: Aika
Writing:
  name: Kirjoittaminen
