archive:
  description: Архив официального репозитория свободного программного обеспечения F-Droid. Приложения в нем устаревшие и могут содержать известные уязвимости и проблемы безопасности!
  icon: fdroid-icon.png
  name: Архив F-Droid
repo:
  description: Официальный репозиторий свободного программного обеспечения F-Droid. Все в этом репозитории всегда собирается из исходного кода.
  icon: fdroid-icon.png
  name: F-Droid
