Ads:
  description: App ino ine zvakashambadzwa zvemamwe makambani
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  description: App inosesedza zvinowedzerwa paapp ino zvinobhadharwa
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: App ino inenhumbi dzinobhadharwa
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: App ino inotemba nemamwe maapps anobhadharwa
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: App ino inosesedza zvirango zvemasaisai zvinobhadharwa
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: App ino inotevera nekududzira zvauri kuita
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Nyuko yemurau irikumberi haisi yemahara
  icon: ic_antifeature_upstreamnonfree.png
