Connectivity:
  name: Mahakiro
Development:
  name: Tsvitsa
Games:
  name: Mitambo
Graphics:
  name: Magraphics
Internet:
  name: Dandemutande
Money:
  name: Mari
Multimedia:
  name: Midhiya yakasiyana
Navigation:
  name: Mafambiro
Phone & SMS:
  name: Nhare neTsamba pfupi
Reading:
  name: Kuverenga
Science & Education:
  name: zveScience neFundo
Security:
  name: Zvekukwdekwera
Sports & Health:
  name: Nhabvu neUtano
System:
  name: Sistemu
Theming:
  name: Kudingindira
Time:
  name: Nguva
Writing:
  name: Kunyora
