Ads:
  description: Dizze applikaasje hat advertinsjes
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Dizze applikaasje hat net in sterke feiligens 没ndertekening
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Dizze applikaasje hat in bekend feiligens probleem
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: De boarne koade is net langer beskikber, gjin fernijingen mooglik.
NonFreeAdd:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije add-ons
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Dizze applikaasje hinget 么f fan oare net-frije applikaasjes
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije netwurk tsjinsten
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Dizze applikaasje folget en rapportearret jo aktiviteit
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.png
