Ads:
  name: Iragarkiak
  description: Aplikazio honek iragarkiak ditu
DisabledAlgorithm:
  name: Segurua ez den algoritmo batez sinatua
  description: Aplikazio honek segurtasun sinadura ahula du
KnownVuln:
  name: Ahultasun ezaguna
  description: Aplikazio honek segurtasun arazo ezagun bat du
NoSourceSince:
  name: Iturburu kodea ez dago jada eskuragarri, ezin izango da eguneratu.
NonFreeAdd:
  name: Libreak ez diren gehigarriak
  description: Aplikazio honen libreak ez diren gehigarriak bultzatzen ditu
NonFreeAssets:
  name: Libreak ez diren aktiboak
  description: Aplikazio honek baliabide ez libreak ditu
NonFreeDep:
  name: Libreak ez diren menpekotasunak
  description: Aplikazio hau beste aplikazio ez libreen menpekoa da
NonFreeNet:
  name: Libreak ez diren sareko zerbitzuak
  description: Aplikazio honek sare zerbitzu ez libreak sustatzen ditu
Tracking:
  name: Arrastoaren jarraipena
  description: Aplikazio honek zure jardueraren jarraipena egiten du eta berri ematen
    du
UpstreamNonFree:
  name: Librea ez den iturburua
  description: Jatorrizko iturburu kodea ez da guztiz librea
