Connectivity:
  icon: category_connectivity.png
  name: 连接
Development:
  name: 开发
Games:
  icon: category_games.png
  name: 游戏
Graphics:
  icon: category_graphics.png
  name: 图像
Internet:
  name: 网络
Money:
  icon: category_money.png
  name: 理财
Multimedia:
  name: 多媒体
Navigation:
  name: 导航
Phone & SMS:
  name: 通话与短信
Reading:
  icon: category_reading.png
  name: 阅读
Science & Education:
  icon: category_science_education.png
  name: 科学与教育
Security:
  icon: category_security.png
  name: 安全
Sports & Health:
  name: 运动与健康
System:
  icon: category_system.png
  name: 系统
Theming:
  icon: category_theming.png
  name: 主题
Time:
  name: 时间
Writing:
  icon: category_writing.png
  name: 记录
