Ads:
  name: Reklamer
  description: Appen indeholder reklamer
DisabledAlgorithm:
  name: Signeret med en usikker algoritme
  description: Denne app har en svag sikkerhedssignatur
KnownVuln:
  name: Kendt sårbarhed
  description: Denne app indeholder en kendt sårbarhed
NSFW:
  name: NSFW
  description: Denne app har et indhold som ikke bør publiceres eller være synlig
    overalt
NoSourceSince:
  name: Kildekoden er ikke længere tilgængelig; ingen opdateringer mulige.
NonFreeAdd:
  name: Ikke frie tilføjelser
  description: Appen fremmer ikke-frie tilføjelser
NonFreeAssets:
  name: Ikke frie genstande
  description: Denne app indeholder ikke-frit indhold
NonFreeDep:
  name: Ikke frie afhængigheder
  description: Denne app er afhængig af andre ikke-frie apps
NonFreeNet:
  name: Ikke-frie netværkstjenester
  description: Appen fremmer ikke-frie netværkstjenester
Tracking:
  name: Sporing
  description: Denne app sporer og indberetter din aktivitet
UpstreamNonFree:
  name: Ikke fri opstrøm
  description: Opstrømskildekoden er ikke fuldstændig fri
