Connectivity:
  name: Tillslutningsmuligheder
Development:
  name: Udvikling
Games:
  name: Spil
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Penge
Multimedia:
  name: Multimedier
Navigation:
  name: Navigation
Phone_SMS:
  name: Telefon og SMS
Reading:
  name: Læsning
Science_Education:
  name: Videnskab og uddannelse
Security:
  name: Sikkerhed
Sports_Health:
  name: Sport og sundhed
System:
  name: System
Theming:
  name: Temaer
Time:
  name: Tid
Writing:
  name: Skrivning
