Ads:
  name: Reklamoj
  description: Tiu ĉi aplikaĵo enhavas reklamojn
DisabledAlgorithm:
  name: Subskribita per malsekura algoritmo
  description: Tiu ĉi aplikaĵo posedas malfortan sekurecan subskribon
KnownVuln:
  name: Konata sekureca vundeblo
  description: Tiu ĉi aplikaĵo posedas sekurecan vundeblon
NSFW:
  name: NSFW
  description: Tiu ĉi aplikaĵo liveras enhavon, kiu ne estas taŭga por rigardi publike
NoSourceSince:
  name: La fontkodo ne estas plu disponebla, neniu ebla ĝisdatigo.
NonFreeAdd:
  name: Neliberaj aldonaĵoj
  description: Tiu ĉi aplikaĵo favoras neliberajn aldonaĵojn
NonFreeAssets:
  name: Nelibera enhavo
  description: Tiu ĉi aplikaĵo enhavas neliberan enhavon
NonFreeDep:
  name: Neliberaj dependecoj
  description: Tiu ĉi aplikaĵo dependas de aliaj neliberaj aplikaĵoj
NonFreeNet:
  name: Neliberaj retservoj
  description: Tiu ĉi aplikaĵo favoras neliberajn retservojn
Tracking:
  name: Spurado
  description: Tiu ĉi aplikaĵo spuras kaj raportas vian agadon
UpstreamNonFree:
  name: Parte libera fontkodo
  description: La fontkodo ne estas tute libera
