Connectivity:
  name: Konekteco
Development:
  name: Programado
Games:
  name: Ludoj
Graphics:
  name: Grafiko
Internet:
  name: Interreto
Money:
  name: Mono
Multimedia:
  name: Plurmedioj
Navigation:
  name: Navigado
Phone & SMS:
  name: Telefono k SMS
Reading:
  name: Legado
Science & Education:
  name: Scienco k edukado
Security:
  name: Sekureco
Sports & Health:
  name: Sporto k sano
System:
  name: Sistemo
Theming:
  name: Etosoj k aspekto
Time:
  name: Tempo
Writing:
  name: Skribado
