Ads:
  description: Mae\'r ap hwn yn cynnwys hysbysebion
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Mae gan yr ap hwn llofnod diogelwch wan
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Mae\'r ap hwn yn cynnwys gwendid diogelwch hysbys
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Dyw\'r cod gwreiddiol ddim bellach ar gael a dim diweddariadau\'n bosib.
NonFreeAdd:
  description: Mae\'r ap hwn yn hyrwyddo ychwanegiadau sy\'n codi tâl
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Mae\'r ap hwn yn cynnwys asedau sydd am ddim
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Mae\'r ap hwn yn dibynnu ar apiau eraill sy\'n codi tâl
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Mae\'r ap hwn yn hyrwyddo gwasanaethau rhwydwaith sy\'n codi tâl
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Mae\'r ap hwn yn tracio ac adrodd dy weithgaredd
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Dyw\'r cod uwchffrydio ddim yn gwbl am ddim
  icon: ic_antifeature_upstreamnonfree.png
