Connectivity:
  name: Cysylltedd
Development:
  name: Datblygiad
Games:
  name: Gemau
Graphics:
  name: Graffigau
Internet:
  name: Rhyngrwyd
Money:
  name: Arian
Multimedia:
  name: Aml-gyfrwng
Navigation:
  name: Llywio
Phone_SMS:
  name: Ffôn ac SMS
Reading:
  name: Darllen
Science_Education:
  name: Gwyddoniaeth ac Addysg
Security:
  name: Diogelwch
Sports_Health:
  name: Chwaraeon a Iechyd
System:
  name: System
Theming:
  name: Themáu
Time:
  name: Amser
Writing:
  name: Ysgrifennu
