Connectivity:
  name: Konektivitas
Development:
  name: Pengembangan
Games:
  name: Permainan
Graphics:
  name: Grafis
Internet:
  name: Internet
Money:
  name: Finansial
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasi
Phone_SMS:
  name: Telepon & SMS
Reading:
  name: Membaca
Science_Education:
  name: Sains & Edukasi
Security:
  name: Keamanan
Sports_Health:
  name: Olahraga & Kesehatan
System:
  name: Sistem
Theming:
  name: Personalisasi
Time:
  name: Waktu
Writing:
  name: Menulis
