Connectivity:
  icon: category_connectivity.png
  name: Konektivitas
Development:
  icon: category_development.png
  name: Pengembangan
Games:
  icon: category_games.png
  name: Permainan
Graphics:
  icon: category_graphics.png
  name: Grafis
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Finansial
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasi
Phone & SMS:
  name: Telepon & SMS
Reading:
  icon: category_reading.png
  name: Membaca
Science & Education:
  icon: category_science_education.png
  name: Sains & Edukasi
Security:
  icon: category_security.png
  name: Keamanan
Sports & Health:
  name: Olahraga & Kesehatan
System:
  icon: category_system.png
  name: Sistem
Theming:
  icon: category_theming.png
  name: Personalisasi
Time:
  name: Waktu
Writing:
  icon: category_writing.png
  name: Menulis
