archive:
  name: Arsip F-Droid
  description: Arsip repositori Perangkat Lunak Bebas F-Droid resmi. Aplikasi yang ada di sini merupakan aplikasi lawas dan dapat berisi kerentanan dan masalah keamanan yang diketahui!
repo:
  name: F-Droid
  description: Repositori Perangkat Lunak Bebas F-Droid resmi. Semuanya dalam repositori ini selalu dibangun dari kode sumber.
