Connectivity:
  icon: category_connectivity.png
  name: Conectividade
Development:
  icon: category_development.png
  name: Desenvolvimento
Games:
  icon: category_games.png
  name: Jogos
Graphics:
  icon: category_graphics.png
  name: Gráficos
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Finanças
Multimedia:
  name: Multimédia
Navigation:
  icon: category_navigation.png
  name: Navegação
Phone & SMS:
  name: Telefone e SMS
Reading:
  icon: category_reading.png
  name: Leitura
Science & Education:
  icon: category_science_education.png
  name: Ciência e educação
Security:
  icon: category_security.png
  name: Segurança
Sports & Health:
  name: Desporto e saúde
System:
  icon: category_system.png
  name: Sistema
Theming:
  icon: category_theming.png
  name: Temas
Time:
  name: Tempo
Writing:
  icon: category_writing.png
  name: Escrita
