Connectivity:
  name: Pripojiteľnosť
Development:
  name: Vývoj
Games:
  name: Hry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Financie
Multimedia:
  name: Multimédiá
Navigation:
  name: Navigácia
Phone_SMS:
  name: Telefón a SMS
Reading:
  name: Čítanie
Science_Education:
  name: Veda a výuka
Security:
  name: Bezpečnosť
Sports_Health:
  name: Šport & Zdravie
System:
  name: Systém
Theming:
  name: Témy
Time:
  name: Čas
Writing:
  name: Písanie
