Connectivity:
  name: Bağlanabilirlik
Development:
  name: Geliştirme
Games:
  name: Oyunlar
Graphics:
  name: Çizim
Internet:
  name: İnternet
Money:
  name: Finans
Multimedia:
  name: Çoklu ortam
Navigation:
  name: Navigasyon
Phone_SMS:
  name: Telefon ve SMS
Reading:
  name: Okuma
Science_Education:
  name: Bilim ve eğitim
Security:
  name: Güvenlik
Sports_Health:
  name: Spor ve Sağlık
System:
  name: Sistem
Theming:
  name: Tema
Time:
  name: Zaman
Writing:
  name: Yazım
