Connectivity:
  icon: category_connectivity.png
  name: Bağlanabilirlik
Development:
  icon: category_development.png
  name: Geliştirme
Games:
  icon: category_games.png
  name: Oyunlar
Graphics:
  icon: category_graphics.png
  name: Çizim
Internet:
  icon: category_internet.png
  name: İnternet
Money:
  icon: category_money.png
  name: Finans
Multimedia:
  name: Çoklu ortam
Navigation:
  name: Navigasyon
Phone & SMS:
  name: Telefon ve SMS
Reading:
  icon: category_reading.png
  name: Okuma
Science & Education:
  icon: category_science_education.png
  name: Bilim ve eğitim
Security:
  icon: category_security.png
  name: Güvenlik
Sports & Health:
  name: Spor ve Sağlık
System:
  icon: category_system.png
  name: Sistem
Theming:
  icon: category_theming.png
  name: Tema
Time:
  name: Zaman
Writing:
  icon: category_writing.png
  name: Yazım
