archive:
  description: Resmi F-Droid Özgür Yazılım deposunun arşivi. Buradaki uygulamalar eskidir ve bilinen güvenlik açıkları ve sorunları içerebilir!
  icon: fdroid-icon.png
  name: F-Droid Arşivi
repo:
  description: Resmi F-Droid Özgür Yazılım deposu. Bu depodaki her şey her zaman kaynak kodlarından oluşturulmuştur.
  icon: fdroid-icon.png
  name: F-Droid
