Ads:
  description: Esta aplicación contiene publicidad
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  description: Esta aplicación promueve complementos no gratuitos
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Esta aplicación contiene activos no libres
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no gratuitas
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Esta aplicación promueve servicios de red no gratuitos
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Esta aplicación realiza un seguimiento e informa de su actividad
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: El código fuente ascendente no es totalmente gratuito
  icon: ic_antifeature_upstreamnonfree.png
