Ads:
  name: Auglýsingar
  description: Þetta forrit inniheldur auglýsingar
DisabledAlgorithm:
  name: Undirritað með óöruggu reikniriti
  description: Þetta forrit er með veika öryggisundirritun
KnownVuln:
  name: Þekktir veikleikar
  description: Þetta forrit inniheldur þekktan öryggisveikleika
NSFW:
  name: NSFW
  description: Þetta forrit inniheldur efni sem ekki ætti að gefa út eða birta opinberlega
NoSourceSince:
  name: Grunnkóðinn er ekki lengur tiltækur, engar uppfærslur eru mögulegar.
NonFreeAdd:
  name: Ófrjálsar viðbætur
  description: Þetta forrit ýtir undir notkun ófrjálsra viðbóta
NonFreeAssets:
  name: Ófrjáls tilföng
  description: Þetta forrit inniheldur ófrjáls tilföng
NonFreeDep:
  name: Ófrjálsar kerfiskröfur
  description: Þetta forrit er háð öðrum ófrjálsum forritum
NonFreeNet:
  name: Ófrjálsar netþjónustur
  description: Þetta forrit ýtir undir notkun ófrjálsrar þjónustu
Tracking:
  name: Eftirlit
  description: Þetta forrit fylgist með og gefur skýrslu um hegðun þína
UpstreamNonFree:
  name: Uppruni ófrjáls
  description: Grunnkóði útgefanda er ekki fullkomlega frjáls
