Ads:
  description: Þetta forrit inniheldur auglýsingar
  icon: ic_antifeature_ads.png
  name: Auglýsingar
DisabledAlgorithm:
  description: Þetta forrit er með veika öryggisundirritun
  icon: ic_antifeature_disabledalgorithm.png
  name: Undirritað með óöruggu reikniriti
KnownVuln:
  description: Þetta forrit inniheldur þekktan öryggisveikleika
  icon: ic_antifeature_knownvuln.png
  name: Þekktir veikleikar
NSFW:
  description: Þetta forrit inniheldur efni sem ekki ætti að gefa út eða birta opinberlega
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Grunnkóðinn er ekki lengur tiltækur, engar uppfærslur eru mögulegar.
NonFreeAdd:
  description: Þetta forrit ýtir undir notkun ófrjálsra viðbóta
  icon: ic_antifeature_nonfreeadd.png
  name: Ófrjálsar viðbætur
NonFreeAssets:
  description: Þetta forrit inniheldur ófrjáls tilföng
  icon: ic_antifeature_nonfreeassets.png
  name: Ófrjáls tilföng
NonFreeDep:
  description: Þetta forrit er háð öðrum ófrjálsum forritum
  icon: ic_antifeature_nonfreedep.png
  name: Ófrjálsar kerfiskröfur
NonFreeNet:
  description: Þetta forrit ýtir undir notkun ófrjálsrar þjónustu
  icon: ic_antifeature_nonfreenet.png
  name: Ófrjálsar netþjónustur
Tracking:
  description: Þetta forrit fylgist með og gefur skýrslu um hegðun þína
  icon: ic_antifeature_tracking.png
  name: Eftirlit
UpstreamNonFree:
  description: Grunnkóði útgefanda er ekki fullkomlega frjáls
  icon: ic_antifeature_upstreamnonfree.png
  name: Uppruni ófrjáls
TetheredNet:
  description: Þetta forrit ýtir undir notkun eða er alveg háð tilteknu tilviki netþjónustu.
  name: TetheredNet-þjónusta
