Ads:
  description: بۇ ئەپتە ئېلان بار
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  description: بۇ ئەپ ھەقسىز بولمىغان قىستۇرمىلارنى تەۋسىيە قىلىدۇ
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: بۇ ئەپ ھەقسىز بولمىغان باشقا ئەپلەرگە بېقىنىدۇ
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: بۇ ئەپ ھەقسىز بولمىغان تور مۇلازىمەتلىرىنى تەۋسىيە قىلىدۇ
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: بۇ ئەپ پائالىيەتلىرىڭىزنى ئىزلاپ، دوكلات قىلىدۇ
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.png
