Ads:
  name: Anúncios
  description: Este aplicativo contém anúncios
DisabledAlgorithm:
  name: Assinado Usando um Algoritmo Inseguro
  description: Este aplicativo tem uma assinatura de segurança fraca
KnownVuln:
  name: Vulnerabilidade conhecida
  description: Este aplicativo contém uma falha de segurança já conhecida
NSFW:
  name: NSFW
  description: Este aplicativo contém conteúdo impróprio para menores de idade
NoSourceSince:
  name: Não é possível atualizar, o código fonte não está mais disponível.
NonFreeAdd:
  name: Complementos não livres
  description: Este aplicativo promove complementos não livres
NonFreeAssets:
  name: Conteúdos não livres
  description: Este aplicativo contém conteúdo não livre
NonFreeDep:
  name: Dependências não livres
  description: Este aplicativo depende de aplicativos não livres
NonFreeNet:
  name: Serviços de rede não livres
  description: Este aplicativo promove serviços de rede não livres
Tracking:
  name: Rastreamento
  description: Este aplicativo rastreia e relata sua atividade
UpstreamNonFree:
  name: Upstream não livre
  description: O código fonte original não é totalmente livre
