Connectivity:
  name: Conectividade
Development:
  name: Desenvolvimento
Games:
  name: Jogos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Dinheiro
Multimedia:
  name: Multimídia
Navigation:
  name: Navegação
Phone_SMS:
  name: Telefone & SMS
Reading:
  name: Leitura
Science_Education:
  name: Ciência & Educação
Security:
  name: Segurança
Sports_Health:
  name: Esportes & Saúde
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempo
Writing:
  name: Escrita
