Ads:
  name: Anúncios
  description: Esta aplicação contém publicidade
DisabledAlgorithm:
  name: Assinado usando um algoritmo inseguro
  description: Esta aplicação tem uma assinatura de segurança fraca
KnownVuln:
  name: Vulnerabilidade conhecida
  description: Esta aplicação contém uma falha de segurança conhecida
NSFW:
  name: NSFW
  description: Esta aplicação contém conteúdo que não deve ser divulgado ou visível
    em todos os lugares
NoSourceSince:
  name: O código-fonte já não está disponível e não é possível atualizar.
NonFreeAdd:
  name: Complementos não livres
  description: Esta aplicação promove add-ons não livres
NonFreeAssets:
  name: Ativos não livres
  description: Esta aplicação contém conteúdo não livre
NonFreeDep:
  name: Dependências não livres
  description: Esta aplicação depende de aplicações não livres
NonFreeNet:
  name: Serviços de rede não livres
  description: Esta aplicação promove serviços de rede não livres
Tracking:
  name: Rastreamento
  description: Esta aplicação monitoriza e reporta a sua atividade
UpstreamNonFree:
  name: Upstream não livre
  description: O código-fonte não é totalmente livre
