Ads:
  name: Anuncis
  description: Aquesta aplicació conté publicitat
DisabledAlgorithm:
  name: Signat amb un algoritme insegur
  description: La signatura de seguretat de l\'aplicació és feble
KnownVuln:
  name: Vulnerabilitat coneguda
  description: Aquesta aplicació té un problema de seguretat conegut
NSFW:
  name: NSFW
  description: Aquesta aplicació conté contingut que no s\'ha de fer públic ni visible
    a tot arreu
NoSourceSince:
  name: El codi font ja no està disponible, no és possible actualitzar.
NonFreeAdd:
  name: Complements no lliures
  description: Aquesta aplicació promou complements no lliures
NonFreeAssets:
  name: Recursos no gratuïts
  description: Aquesta aplicació conté parts no lliures
NonFreeDep:
  name: Dependències no lliures
  description: Aquesta aplicació depèn d\'altres aplicacions no lliures
NonFreeNet:
  name: Serveis de xarxa no lliures
  description: Aquesta aplicació promou serveis de xarxa no lliures
Tracking:
  name: Seguiment
  description: Aquesta aplicació segueix i informa sobre la vostra activitat
UpstreamNonFree:
  name: Upstream no lliure
  description: El codi font no és del tot lliure
