Ads:
  description: Այս ափփը պարունակում է գովազդ
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  icon: ic_antifeature_nonfreenet.png
Tracking:
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.png
