Ads:
  description: دا کاریال انګروزي لري
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: دا کاریال د خونديينې کمزوری لاسليک لري
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: سرچينې کوډ نور لاسلرلی نه دی، اوسمهالول شونې نه دي.
NonFreeAdd:
  description: دا کاریال ناازاده پر-زیاتوونې پرمخوړي
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: دا کاریال ناازاده پانګې لري
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: دا کاریال په نورو ناازاده کاریالونو باندې اړه لري
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: دا کاریال ناازادې جال پالنې پرمخوړي
  icon: ic_antifeature_nonfreenet.png
Tracking:
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.png
