Development:
  name: پرمختيا
Games:
  name: لوبې
Graphics:
  name: كښنيزونه
Internet:
  name: نړیجال
Multimedia:
  name: ګڼرسنۍ
Navigation:
  name: چلونه
Phone & SMS:
  name: لرغږون او استوزې
Reading:
  name: لوستنه
Science & Education:
  name: پوهه او زده کړه
Security:
  name: خونديينه
Sports & Health:
  name: کړاو او روغتيا
System:
  name: غونډال
Time:
  name: مهال
Writing:
  name: ليکنه
