Ads:
  description: Энэхүү програм нь зар сурталчилгааг агуулдаг
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Энэ апп аюулгүй байдлын гарын үсэг сул байна
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Энэхүү програм нь мэдэгдэж буй аюулгүй байдлын эмзэг байдлыг агуулдаг
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Эх код одоо байхгүй, шинэчлэх боломжгүй байна.
NonFreeAdd:
  description: Энэхүү програм нь үнэгүй нэмэлт бус нэмэлтүүдийг сурталчилдаг
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Энэ апп нь үнэгүй бус хөрөнгийг агуулдаг
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Энэ програм нь бусад үнэгүй програмуудаас хамаарна
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Энэхүү програм нь үнэгүй сүлжээний үйлчилгээг сурталчлах болно
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Энэ апп нь таны үйл ажиллагааг хянах, мэдээлэх
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Урсгал эх код нь бүхэлдээ Үнэгүй биш юм
  icon: ic_antifeature_upstreamnonfree.png
