Ads:
  name: বিজ্ঞাপন
  description: এই অ্যাপে বিজ্ঞাপন আছে
DisabledAlgorithm:
  name: অনিরাপদভাবে স্বাক্ষরিত
  description: এই অ্যাপের নিরাপত্তা স্বাক্ষর খুব দুর্বল
KnownVuln:
  name: জানা অনিরাপত্তা আছে
  description: এই অ্যাপের একটি জানা নিরাপত্তা দুর্বলতা রয়েছে
NoSourceSince:
  name: উৎস কোড এখন অনুপভ্য, হালনাগাদ সম্ভব নয়।
NonFreeAdd:
  name: অ-মুক্ত সংযোজন
  description: এই অ্যাপ অ-মুক্ত অ্যাড-অন ব্যবহারে উৎসাহিত করে
NonFreeAssets:
  name: অমুক্ত অংশ
  description: এই অ্যাপে অ-মুক্ত উপাদান আছে
NonFreeDep:
  name: অ-মুক্ত নির্ভরশীল শাখা
  description: এই অ্যাপ অন্যান্য অ-মুক্ত অ্যাপের উপর নির্ভর করে
NonFreeNet:
  name: অ-মুক্ত নেটওয়ার্ক সেবা
  description: এই অ্যাপ অ-মুক্ত নেটওয়ার্ক সেবা নিতে উৎসাহিত করে
Tracking:
  name: নজরদারী
  description: এই অ্যাপটি আপনার কার্যকলাপ ট্র্যাক করে এবং বলে দেয়
UpstreamNonFree:
  name: উজান অ-মুক্ত
  description: উজানের কোড সম্পূর্ণরূপে মুক্ত না
