Ads:
  description: Deze app bevat advertenties
  icon: ic_antifeature_ads.png
  name: Advertenties
DisabledAlgorithm:
  description: Deze app heeft een zwakke beveiligingshandtekening
  icon: ic_antifeature_disabledalgorithm.png
  name: Ondertekend met een onveilige sleutel
KnownVuln:
  description: Deze app bevat een bekend probleem in de beveiliging
  icon: ic_antifeature_knownvuln.png
  name: Bekende Kwetsbaarheid
NSFW:
  icon: ic_antifeature_nsfw.png
  description: Deze app bevat gegevens die niet overal mag worden gepubliceerd of zichtbaar is
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: De broncode is niet meer beschikbaar, updates zijn niet mogelijk.
NonFreeAdd:
  description: Deze app promoot niet-vrije add-ons
  icon: ic_antifeature_nonfreeadd.png
  name: Niet-vrije uitbreidingen
NonFreeAssets:
  description: Deze app bevat niet-vrije elementen
  icon: ic_antifeature_nonfreeassets.png
  name: Niet-vrije onderdelen
NonFreeDep:
  description: Deze app vereist andere niet-vrije apps
  icon: ic_antifeature_nonfreedep.png
  name: Niet-vrije afhankelijkheden
NonFreeNet:
  description: Deze app promoot niet-vrije netwerkdiensten
  icon: ic_antifeature_nonfreenet.png
  name: Niet-vrije netwerkdiensten
Tracking:
  description: Deze app houdt je activiteiten bij en rapporteert ze
  icon: ic_antifeature_tracking.png
  name: Tracering
UpstreamNonFree:
  description: De broncode stroomopwaarts is niet helemaal vrij (open-bron)
  icon: ic_antifeature_upstreamnonfree.png
  name: Niet-vrij origineel
TetheredNet:
  description: Deze app promoot van een bepaald exemplaar van een netwerkdienst of is hiervan volledig afhankelijk.
  name: Netwerkbinding
