Ads:
  name: Advertenties
  description: Deze app bevat advertenties
DisabledAlgorithm:
  name: Ondertekend met een onveilige sleutel
  description: Deze app heeft een zwakke beveiligingshandtekening
KnownVuln:
  name: Bekende Kwetsbaarheid
  description: Deze app bevat een bekend probleem in de beveiliging
NoSourceSince:
  name: De broncode is niet meer beschikbaar, updates zijn niet mogelijk.
NonFreeAdd:
  description: Deze app promoot niet-vrije add-ons
NonFreeAssets:
  description: Deze app bevat niet-vrije elementen
NonFreeDep:
  description: Deze app vereist andere niet-vrije apps
NonFreeNet:
  description: Deze app promoot niet-vrije netwerkdiensten
Tracking:
  description: Deze app houdt je activiteiten bij en rapporteert ze
UpstreamNonFree:
  description: De broncode stroomopwaarts is niet helemaal vrij (open-bron)
