Ads:
  name: Ads
  description: This app contains advertising
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  name: Signed Using An Unsafe Algorithm
  description: This app has a weak security signature
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  name: Known Vulnerability
  description: This app contains a known security vulnerability
  icon: ic_antifeature_knownvuln.xml
NSFW:
  name: NSFW
  description: This app contains content that should not be publicized or visible
    everywhere
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  name: The source code is no longer available, no updates possible.
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  name: Non-Free Addons
  description: This app promotes non-free add-ons
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  name: Non-Free Assets
  description: This app contains non-free assets
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  name: Non-Free Dependencies
  description: This app depends on other non-free apps
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  name: Non-Free Network Services
  description: This app promotes or depends entirely on a non-free network service
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  name: Tracking
  description: This app tracks and reports your activity
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  name: Upstream Non-Free
  description: The upstream source code is not entirely Free
  icon: ic_antifeature_upstreamnonfree.xml
