Connectivity:
  name: Connectivity
  icon: category_connectivity.png
Development:
  name: Development
  icon: category_development.png
Games:
  name: Games
  icon: category_games.png
Graphics:
  name: Graphics
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Money
  icon: category_money.png
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
  icon: category_navigation.png
Phone & SMS:
  name: Phone & SMS
Reading:
  name: Reading
  icon: category_reading.png
Science & Education:
  name: Science & Education
  icon: category_science_education.png
Security:
  name: Security
  icon: category_security.png
Sports & Health:
  name: Sports & Health
System:
  name: System
  icon: category_system.png
Theming:
  name: Theming
  icon: category_theming.png
Time:
  name: Time
Writing:
  name: Writing
  icon: category_writing.png
