Connectivity:
  icon: category_connectivity.png
  name: Connectivity
Development:
  icon: category_development.png
  name: Development
Games:
  icon: category_games.png
  name: Games
Graphics:
  icon: category_graphics.png
  name: Graphics
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Money
Multimedia:
  name: Multimedia
Navigation:
  icon: category_navigation.png
  name: Navigation
Phone & SMS:
  name: Phone & SMS
Reading:
  icon: category_reading.png
  name: Reading
Science & Education:
  icon: category_science_education.png
  name: Science & Education
Security:
  icon: category_security.png
  name: Security
Sports & Health:
  name: Sports & Health
System:
  icon: category_system.png
  name: System
Theming:
  icon: category_theming.png
  name: Theming
Time:
  name: Time
Writing:
  icon: category_writing.png
  name: Writing
