Connectivity:
  icon: category_connectivity.png
  name: Свързаност
Development:
  icon: category_development.png
  name: Разработка
Games:
  icon: category_games.png
  name: Игри
Graphics:
  icon: category_graphics.png
  name: Изображения
Internet:
  icon: category_internet.png
  name: Интернет
Money:
  icon: category_money.png
  name: Финанси
Multimedia:
  name: Мултимедия
Navigation:
  icon: category_navigation.png
  name: Местоположение
Phone & SMS:
  name: Телефон и SMS
Reading:
  icon: category_reading.png
  name: Четене
Science & Education:
  icon: category_science_education.png
  name: Наука и образование
Security:
  icon: category_security.png
  name: Сигурност
Sports & Health:
  name: Спорт и здраве
System:
  icon: category_system.png
  name: Системни
Theming:
  icon: category_theming.png
  name: Теми
Time:
  name: Управление на времето
Writing:
  icon: category_writing.png
  name: Писане
