Ads:
  description: མཉེན་ཆས་འདིའི་ནང་ཁྱབ་བསྒྲགས་ཡོད།
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  description: མཉེན་ཆས་འདི་རིན་མེད་མ་ཡིན་པའི་ཆ་རྐྱེན་འཕར་མ་རྒྱབ་སྐྱོར་བྱེད་ཀྱི་ཡོད།
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: མཉེན་ཆས་འདིའི་ནང་རིན་མེད་མ་ཡིན་པའི་རྒྱུ་ཆ་ཡོད།
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: མཉེན་ཆས་འདི་རིན་མེད་མ་ཡིན་པའི་མཉེན་ཆས་གཞན་ལ་བརྟེན་ནས་ཡོད།
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: མཉེས་ཆས་འདིས་རིན་མེད་མ་ཡིན་པའི་དྲྭ་རྒྱའི་ཞབས་ཞུ་ཁྱབ་བསྒྲགས་བྱེད་ཀྱི་ཡོད།
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: མཉེན་ཆས་འདིས་ཁྱེད་རང་རྗེས་འདེད་བཏང་ནས་ལས་ཀ་གང་བྱས་ཀྱང་བརྡ་ལན་སྤྲད་ཀྱི་རེད།
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: འབྱུང་ཁུངས་ཨང་རྟགས་འདི་ཆ་ཚང་རིན་མེད་མ་རེད།
  icon: ic_antifeature_upstreamnonfree.png
