Ads:
  description: ဒီ app သည္ ေၾကျငာမ်ားပါဝင္သည္
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
NonFreeAdd:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ေနာက္ထပ္ပါဝင္သည့္အရာမ်ားပါဝင္သည္
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ပံုမ်ားပါဝင္သည္
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: ဒီ app သည္ တျခားအခမဲ့မဟုတ္ေသာ app မ်ားေပၚမူတည္သည္
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာကြန္ရက္ ဝန္ေဆာင္မႈကိုေထာက္ပံ့သည္
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: ဒီ app သည္ သင့္လႈပ္ရွားမႈမ်ားကိုလိုက္ၾကည့္ျပီးမွတ္တမ္း မွတ္သည္
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: ဆိုစ့္ကုဒ္သည္ လံုးဝအခမဲ့မဟုတ္ပါ
  icon: ic_antifeature_upstreamnonfree.png
