Ads:
  name: Reklámok
  description: Az alkalmazás reklámot tartalmaz
DisabledAlgorithm:
  name: Nem biztonságos algoritmussal aláírt
  description: Az alkalmazásnak gyenge a biztonsági aláírása
KnownVuln:
  name: Ismert sérülékenység
  description: Az alkalmazás ismert biztonsági rést tartalmaz
NSFW:
  name: NSFW
  description: Ez az alkalmazás olyan tartalommal rendelkezik, amelyet nem szabad
    mindenhol megjeleníteni
NoSourceSince:
  name: A forráskód többé nem érhető el, a frissítések nem lehetségesek.
NonFreeAdd:
  name: Nem szabad kiegészítők
  description: Az alkalmazás nem szabad kiegészítőket támogat
NonFreeAssets:
  name: Nem szabad erőforrások
  description: Az alkalmazás nem szabad eszközöket tartalmaz
NonFreeDep:
  name: Nem szabad függőségek
  description: Az alkalmazás egyéb, nem szabad alkalmazásoktól függ
NonFreeNet:
  name: Nem szabad hálózati szolgáltatások
  description: Az alkalmazás nem szabad hálózati szolgáltatásokat támogat
Tracking:
  name: Követés
  description: Az alkalmazás nyomon követi és jelenti a tevékenységeit
UpstreamNonFree:
  name: Nem szabad upstream forráskód
  description: Az upstream forráskód nem teljesen szabad
