Connectivity:
  name: Kapcsolódás
Development:
  name: Fejlesztés
Games:
  name: Játékok
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Pénzügyek
Multimedia:
  name: Multimédia
Navigation:
  name: Navigáció
Phone_SMS:
  name: Telefon és SMS
Reading:
  name: Olvasás
Science_Education:
  name: Tudomány és oktatás
Security:
  name: Biztonság
Sports_Health:
  name: Sport és egészség
System:
  name: Rendszer
Theming:
  name: Stílus
Time:
  name: Idő
Writing:
  name: Írás
