Ads:
  name: Skelbimai
  description: Šioje programėlėje yra reklamų
DisabledAlgorithm:
  name: Pasirašyta naudojant nesaugų algoritmą
  description: Ši programėlė turi silpną saugumo parašą
KnownVuln:
  name: Žinomas pažeidžiamumas
  description: Šioje programėlėje yra žinomas saugumo pažeidžiamumas
NoSourceSince:
  name: Pirminis kodas daugiau nebeprieinamas, atnaujinimai negalimi.
NonFreeAdd:
  name: Ne atviro kodo papildiniai
  description: Ši programėlė skatina įdiegti nelaisvus papildinius
NonFreeAssets:
  name: Ne atviro kodo resursai
  description: Šioje programėlėje yra nelaisvų resursų
NonFreeDep:
  name: Ne atviro kodo priklausomieji
  description: Ši programėlė priklauso nuo nelaisvų programėlių
NonFreeNet:
  name: Ne atviro kodo tinklo paslaugos
  description: Ši programėlė skatina nelaisvas tinklo paslaugas
Tracking:
  name: Sekimas
  description: Ši programėlė seka ir perduoda Jūsų veiksmus
UpstreamNonFree:
  name: Ne atviro kodo pradinis kodas
  description: Pradinis pirminis kodas nėra visiškai laisvas
