Connectivity:
  name: Ryšiai ir tinklas
Development:
  name: Plėtojimas
Games:
  name: Žaidimai
Graphics:
  name: Grafika
Internet:
  name: Internetas
Money:
  name: Pinigai
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone & SMS:
  name: Telefonas ir SMS
Reading:
  name: Skaitymas
Science & Education:
  name: Mokslas ir švietimas
Security:
  name: Saugumas
Sports & Health:
  name: Sportas ir sveikata
System:
  name: Sistema
Theming:
  name: Apipavidalinimas
Time:
  name: Laikas
Writing:
  name: Rašymas
