Ads:
  name: Reklaamid
  description: Selles rakenduses on reklaame
DisabledAlgorithm:
  name: Allkirjastamisel on kasutatud ebaturvalist algoritmi
  description: Sellel rakendusel on nõrk turvasignatuur
KnownVuln:
  name: Tuntud turvanõrkus
  description: Sellel rakendusel on tuntud turvanõrkus
NSFW:
  name: NSFW
  description: Selles rakenduses on sisu, mida ei saa kõikjal avaldada ega peaks olema
    kõikjalt vaadatav
NoSourceSince:
  name: Lähtekood ei ole enam saadaval, uuendused ei ole enam võimalikud.
NonFreeAdd:
  name: Mitte-vabad laiendused
  description: See rakendus edendab mitte-vabu laiendusi
NonFreeAssets:
  name: Mitte-vabad komponendid
  description: Selles rakenduses on mitte-vabu komponente
NonFreeDep:
  name: Sõltuvus mitte-vabadest rakendustest
  description: See rakendus sõltub teistest mitte-vabadest rakendustest
NonFreeNet:
  name: Mitte-vabad võrguteenuseid
  description: See rakendus eelistab mitte-vabu võrguteenuseid
Tracking:
  name: Sisaldab kasutajate tegevuse jälgimist
  description: See rakendus jälgib ja raporteerib su aktiivsusest
UpstreamNonFree:
  name: Mitte-vaba ülesvoolu lähtekood
  description: Ülesvoolu lähtekood ei ole täiesti vaba
