Connectivity:
  name: Ühenduvus
Development:
  name: Arendus
Games:
  name: Mängud
Graphics:
  name: Graafika
Internet:
  name: Internet
Money:
  name: Raha
Multimedia:
  name: Multimeedia
Navigation:
  name: Navigeerimine
Phone_SMS:
  name: Telefon & SMS
Reading:
  name: Lugemine
Science_Education:
  name: Teadus & haridus
Security:
  name: Turvalisus
Sports_Health:
  name: Sport & tervis
System:
  name: Süsteem
Theming:
  name: Teemad
Time:
  name: Aeg
Writing:
  name: Kirjutamine
