Money:
  name: pesa
Graphics:
  name: Michoro
Phone & SMS:
  name: Simu na SMS
Science & Education:
  name: Sayansi na Elimu
Security:
  name: Usalama
Sports & Health:
  name: Michezo na Afya
Time:
  name: Wakati
Connectivity:
  name: Muunganisho
Development:
  name: Maendeleo
Games:
  name: Michezo
Internet:
  name: Mtandao
Multimedia:
  name: mawasiliano ya aina mbili
Navigation:
  name: Urambazaji
Reading:
  name: Kusoma
System:
  name: Mfumo
Theming:
  name: Mandhari
Writing:
  name: Kuandika
