Ads:
  name: Reklamy
  description: Ta aplikacja zawiera reklamy
DisabledAlgorithm:
  name: Podpisany przy użyciu niebezpiecznego algorytmu
  description: Ta aplikacja ma słaby podpis bezpieczeństwa
KnownVuln:
  name: Znana podatność
  description: Ta aplikacja ma znaną podatność bezpieczeństwa
NSFW:
  name: NSFW
  description: Ta aplikacja zawiera treści, które nie powinny być publikowane ani
    widoczne wszędzie
NoSourceSince:
  name: Kod źródłowy nie jest już dostępny, nie są możliwe aktualizacje.
NonFreeAdd:
  name: Niewolne dodatki
  description: Ta aplikacja promuje niewolne dodatki
NonFreeAssets:
  name: Niewolne zasoby
  description: Ta aplikacja zawiera niewolne zasoby
NonFreeDep:
  name: Niewolne zależności
  description: Ta aplikacja wymaga innych, niewolnych aplikacji
NonFreeNet:
  name: Niewolne usługi sieciowe
  description: Ta aplikacja promuje niewolne usługi sieciowe
Tracking:
  name: Śledzenie
  description: Ta aplikacja śledzi i raportuje Twoją aktywność
UpstreamNonFree:
  name: Niewolne upstream
  description: Upstreamowy kod źródłowy nie jest w pełni wolny
