Connectivity:
  name: Łączność
Development:
  name: Programowanie
Games:
  name: Gry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Finanse
Multimedia:
  name: Multimedia
Navigation:
  name: Nawigacja
Phone_SMS:
  name: Telefon i SMS
Reading:
  name: Czytanie
Science_Education:
  name: Nauka i edukacja
Security:
  name: Bezpieczeństwo
Sports_Health:
  name: Sport i zdrowie
System:
  name: System
Theming:
  name: Motywy
Time:
  name: Czas
Writing:
  name: Pisanie
