Connectivity:
  icon: category_connectivity.png
  name: Łączność
Development:
  icon: category_development.png
  name: Programowanie
Games:
  icon: category_games.png
  name: Gry
Graphics:
  icon: category_graphics.png
  name: Grafika
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Finanse
Multimedia:
  name: Multimedia
Navigation:
  name: Nawigacja
  icon: category_navigation.png
Phone & SMS:
  name: Telefon i SMS
Reading:
  icon: category_reading.png
  name: Czytanie
Science & Education:
  icon: category_science_education.png
  name: Nauka i edukacja
Security:
  icon: category_security.png
  name: Bezpieczeństwo
Sports & Health:
  name: Sport i zdrowie
System:
  icon: category_system.png
  name: System
Theming:
  icon: category_theming.png
  name: Motywy
Time:
  name: Czas
Writing:
  icon: category_writing.png
  name: Pisanie
