Ads:
  name: Mga Ad
  description: Naglalaman ng patalastas ang app na ito
DisabledAlgorithm:
  name: Pirmado gamit ang isang di-ligtas na algoritmo
  description: May mahinang pirmang panseguridad ang app na ito
KnownVuln:
  name: May Kahinaan
  description: Naglalaman ng isang kilalang kahinaan sa seguridad ang app na ito
NoSourceSince:
  name: Wala na yung source code, di na itong muling maia-update.
NonFreeAdd:
  name: Mga di-libreng addon
  description: Nagpo-promote ng mga di-libreng addon ang app na ito
NonFreeAssets:
  name: Mga di-libreng asset
  description: Naglalaman ng mga di-libreng asset ang app na ito
NonFreeDep:
  name: Dumedepende sa mga di-libre
  description: Dumedepende sa ibang mga di-libreng app ang app na ito
NonFreeNet:
  name: Mga di-libre serbisyong pang-network
  description: Nagpo-promote ng mga di-libreng serbisyong pang-network ang app na
    ito
Tracking:
  name: Pagta-track
  description: Tina-track at inuulat ng app na ito ang iyong aktibidad
UpstreamNonFree:
  name: Di-libreng upstream
  description: Di talaga malaya ang upstream source code
