Ads:
  name: Publicités
  description: Cette appli comprend des publicités
DisabledAlgorithm:
  name: Signé par un algorithme non sécurisé
  description: La signature de sécurité de cette application est faible
KnownVuln:
  name: Contient des vulnérabilités connues
  description: Cette appli présente une vulnérabilité de sécurité connue
NSFW:
  name: NSFW
  description: Cette application contient des contenus qui ne doivent pas être rendus
    publics ni visibles partout.
NoSourceSince:
  name: Le code source n’est plus accessible, aucune mise à jour n’est possible.
NonFreeAdd:
  name: Addons payants
  description: Cette applications propose des extensions qui ne sont pas libres
NonFreeAssets:
  name: Composants non libres
  description: Cette appli comprend des éléments qui ne sont pas libres
NonFreeDep:
  name: Dépendances payantes
  description: Cette application s\'appuie d\'autres applications qui ne sont pas
    libres
NonFreeNet:
  name: Services réseaux payants
  description: Cette application propose d\'utiliser des services réseaux qui ne sont
    pas libres
Tracking:
  name: Traçage
  description: Cette application suit et transmet votre activité
UpstreamNonFree:
  name: Amont payant
  description: Le code source en amont n’est pas entièrement libre
