Connectivity:
  name: Connectivité
Development:
  name: Développement
Games:
  name: Jeux
Graphics:
  name: Graphisme
Internet:
  name: Internet
Money:
  name: Finances
Multimedia:
  name: Multimédia
Navigation:
  name: Navigation
Phone_SMS:
  name: Téléphone et SMS
Reading:
  name: Lecture
Science_Education:
  name: Science et éducation
Security:
  name: Sécurité
Sports_Health:
  name: Sport et santé
System:
  name: Système
Theming:
  name: Personnalisation
Time:
  name: Temps
Writing:
  name: Écriture
