archive:
  description: L'archive du dépôt officiel de logiciels libres F-Droid. Les applications ici sont anciennes et peuvent contenir des vulnérabilités connues et des problèmes de sécurité!
  name: Archive F-Droid
repo:
  description: Le dépôt officiel de logiciels libres F-Droid. Tout ce qui se trouve dans ce dépôt est toujours construit à partir du code source.
  name: F-Droid
