Ads:
  description: Esta aplicación tiene publicidad
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad débil
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: El código fuente ya no está disponible, ninguna actualización posible.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Esta aplicación contiene recursos no libres
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no libres
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Esta aplicación promueve servicios no libres
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Esta aplicación rastrea e informa de tu actividad
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: El codigo fuente de subida no es completamente libre
  icon: ic_antifeature_upstreamnonfree.png
