DisabledAlgorithm:
  name: Təhlükəli Alqoritm İşlədərək İmzalanıb
  description: Bu tətbiqin zəif təhlükəsizlik imzası var
Ads:
  description: Bu tətbiq reklam ehtiva edir
  name: Reklamlar
KnownVuln:
  description: Bu tətbiqin məlum təhlükəsizlik zəifliyi var
  name: Məlum Zəiflik
NSFW:
  description: Bu tətbiq ictimailəşdirilməməli və ya hər yerdə görünməməli məzmun ehtiva edir
  name: NSFW
NoSourceSince:
  name: Mənbə kodu artıq mövcud deyil, yeniləmələr mümkün deyil.
