Ads:
  description: Ova aplikacija sadržava oglase
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Ova aplikacija ima slab sigurnosni potpis
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Ova aplikacija sadrži poznatu sigurnosnu ranjivost
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Izvorni kod više nije dostupan, nije moguće ažurirati.
NonFreeAdd:
  description: Ova aplikacija promovira neslobodne dodatke
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Ova aplikacija sadrži neslobodne resurse
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Ova aplikacija ovisi o drugim neslobodnim aplikacijama
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Ova aplikacija promovira neslobodne mrežne usluge
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Ova aplikacija prati i javlja Vašu aktivnost
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Uzvodni izvorni kod nije u potpunosti otvoren/slobodan
  icon: ic_antifeature_upstreamnonfree.png
