Connectivity:
  name: Povezivanje
Development:
  name: Razvoj
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Novac
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone_SMS:
  name: Telefon i SMS
Reading:
  name: Čitanje
Science_Education:
  name: Znanost i edukacija
Security:
  name: Sigurnost
Sports_Health:
  name: Sport i zdravlje
System:
  name: Sustav
Theming:
  name: Teme
Time:
  name: Vrijeme
Writing:
  name: Pisanje
