Ads:
  description: Asnas-a yegber adellel
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Asnas-a yesɛa azmul i ixuṣṣen deg tɣellist
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Tangalt taɣbalut dayen ur telli ara, ulac ileqman.
NonFreeAdd:
  description: Asnas-a yegber Izegrar ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Asnas-a yegber iḥricen ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Asnas-a icudd ɣer yisnasen-nniḍen ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Asnas-a isnernay imeẓliyen n uẓeṭṭa ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Asnas-agi ad yeḍfeṛ udiγ ad d-yazen armud-ik
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.png
