archive:
  name: F-Droidアーカイブ
  description: 公式のF-Droidフリーソフトウェアリポジトリのアーカイブです。 アプリは古く、既知の脆弱性やセキュリティの問題を含んでいる場合があります！
repo:
  description: 公式のF-Droidフリーソフトウェアリポジトリ。 このリポジトリにあるソフトウェアは、常にソースコードからビルドされています。
  name: F-Droid
