Connectivity:
  icon: category_connectivity.png
  name: Vernetzung
Development:
  icon: category_development.png
  name: Entwicklung
Games:
  icon: category_games.png
  name: Spiele
Graphics:
  icon: category_graphics.png
  name: Grafik
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  icon: category_navigation.png
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  icon: category_reading.png
  name: Lesen
Science & Education:
  icon: category_science_education.png
  name: Wissenschaft & Bildung
Security:
  icon: category_security.png
  name: Sicherheit
Sports & Health:
  name: Sport & Gesundheit
System:
  icon: category_system.png
  name: System
Theming:
  icon: category_theming.png
  name: Aussehen
Time:
  name: Zeit
Writing:
  icon: category_writing.png
  name: Schreiben
