archive:
  description: Das Archiv des offiziellen F-Droid Free Software Repository. Diese Apps hier sind alt und können bekannte Schwachstellen und Sicherheitsprobleme enthalten!
  icon: fdroid-icon.png
  name: F-Droid Archiv
repo:
  description: Das offizielle F-Droid Repository für Freie Software. Alles in diesem Repository wird immer aus dem Quellcode erstellt.
  icon: fdroid-icon.png
  name: F-Droid
