Ads:
  description: Dette programmet inneholder reklame
  icon: ic_antifeature_ads.png
  name: Reklame
DisabledAlgorithm:
  description: Dette programmet har en svak sikkerhetssignatur
  icon: ic_antifeature_disabledalgorithm.png
  name: Signert med en utrygg algoritme
KnownVuln:
  description: Dette programmet inneholder en kjent sikkerhetsfeil
  icon: ic_antifeature_knownvuln.png
  name: Kjent sårbarhet
NSFW:
  description: Programmet inneholder innhold ledelsen i F-Droid synes bør sensureres
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Kildekoden er ikke lenger tilgjengelig, ingen oppdateringer mulig.
NonFreeAdd:
  description: Dette programmet promoterer ufrie utvidelser
  icon: ic_antifeature_nonfreeadd.png
  name: Ufrie tillegg
NonFreeAssets:
  description: Dette programmet inneholder ufrie gjenstander
  icon: ic_antifeature_nonfreeassets.png
  name: Ufrie gjenstander
NonFreeDep:
  description: Dette programmet avhenger av andre ufrie applikasjoner
  icon: ic_antifeature_nonfreedep.png
  name: Ufrie avhengigheter
NonFreeNet:
  description: Dette programmet promoterer ufrie nettverkstjenester
  icon: ic_antifeature_nonfreenet.png
  name: Ufrie nettverkstjenester
Tracking:
  description: Dette programmet sporer og rapporterer din aktivitet
  icon: ic_antifeature_tracking.png
  name: Sporing
UpstreamNonFree:
  description: Kildekoden er ikke helt fri
  icon: ic_antifeature_upstreamnonfree.png
  name: Kildekoden oppstrøms er ikke helt fri
