Ads:
  name: Reklame
  description: Dette programmet inneholder reklame
DisabledAlgorithm:
  name: Signert med en utrygg algoritme
  description: Dette programmet har en svak sikkerhetssignatur
KnownVuln:
  name: Kjent sårbarhet
  description: Dette programmet inneholder en kjent sikkerhetsfeil
NSFW:
  name: NSFW
  description: Programmet inneholder innhold ledelsen i F-Droid synes bør sensureres
NoSourceSince:
  name: Kildekoden er ikke lenger tilgjengelig, ingen oppdateringer mulig.
NonFreeAdd:
  name: Ufrie tillegg
  description: Dette programmet promoterer ufrie utvidelser
NonFreeAssets:
  name: Ufrie gjenstander
  description: Dette programmet inneholder ufrie gjenstander
NonFreeDep:
  name: Ufrie avhengigheter
  description: Dette programmet avhenger av andre ufrie applikasjoner
NonFreeNet:
  name: Ufrie nettverkstjenester
  description: Dette programmet promoterer ufrie nettverkstjenester
Tracking:
  name: Sporing
  description: Dette programmet sporer og rapporterer din aktivitet
UpstreamNonFree:
  name: Kildekoden oppstrøms er ikke helt fri
  description: Kildekoden er ikke helt fri
