Ads:
  name: Anuncios
  description: Esta aplicación contién anuncios
DisabledAlgorithm:
  name: Signed Using An Unsafe Algorithm
  description: Esta aplicación tien una firma de seguranza que ye feble
KnownVuln:
  name: Known Vulnerability
  description: This app contains a known security vulnerability
NSFW:
  name: NSFW
  description: This app contains content that should not be publicized or visible
    everywhere
NoSourceSince:
  name: El códigu fonte yá nun ta disponible. Nun va haber más anovamientos.
NonFreeAdd:
  name: Complementos privativos
  description: This app promotes non-free add-ons
NonFreeAssets:
  name: Gráficos privativos
  description: Esta aplicación contién gráficos que son privativos
NonFreeDep:
  name: Dependencies privatives
  description: This app depends on other non-free apps
NonFreeNet:
  name: Servicios de rede privativos
  description: This app promotes non-free network services
Tracking:
  name: Tracking
  description: This app tracks and reports your activity
UpstreamNonFree:
  name: Upstream Non-Free
  description: El códigu fonte nun ye llibre dafechu
