Connectivity:
  name: Conectividá
Development:
  name: Desendolcu
Games:
  name: Xuegos
Graphics:
  name: Graphics
Internet:
  name: Internet
Money:
  name: Dineru
Multimedia:
  name: Multimedia
Navigation:
  name: Navegación
Phone & SMS:
  name: Telefonía y SMS
Reading:
  name: Llectura
Science & Education:
  name: Ciencia y educación
Security:
  name: Seguranza
Sports & Health:
  name: Deporte y salú
System:
  name: Sistema
Theming:
  name: Aspeutu
Time:
  name: Time
Writing:
  name: Escritura
