Ads:
  name: Annunci
  description: Questa app contiene pubblicità
DisabledAlgorithm:
  name: Firmato usando un algoritmo non sicuro
  description: Questa applicazione ha una firma digitale debole
KnownVuln:
  name: Vulnerabilità conosciuta
  description: Questa applicazione contiene una falla di sicurezza nota
NSFW:
  name: NSFW
  description: Questa app ha contenuti che non dovrebbero essere pubblicizzati o visibili
    ovunque
NoSourceSince:
  name: Il codice sorgente non è più disponibile, aggiornamenti non possibili.
NonFreeAdd:
  name: Addon non liberi
  description: Questa app promuove add-on non liberi
NonFreeAssets:
  name: Risorse non libere
  description: Questa app contiene risorse non libere
NonFreeDep:
  name: Dipendenze non libere
  description: Questa app dipende da altre app non libere
NonFreeNet:
  name: Servizi di rete non liberi
  description: Questa app promuove servizi di rete non liberi
Tracking:
  name: Tracciamento
  description: Questa app monitora e riferisce sulle tue attività
UpstreamNonFree:
  name: Non libero a monte
  description: Il codice sorgente a monte non è completamente libero
