Connectivity:
  icon: category_connectivity.png
  name: Connettività
Development:
  icon: category_development.png
  name: Sviluppo
Games:
  icon: category_games.png
  name: Giochi
Graphics:
  icon: category_graphics.png
  name: Grafica
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Finanze
Multimedia:
  name: Multimedia
Navigation:
  icon: category_navigation.png
  name: Navigazione
Phone & SMS:
  name: Telefono e SMS
Reading:
  icon: category_reading.png
  name: Lettura
Science & Education:
  icon: category_science_education.png
  name: Scienza ed educazione
Security:
  icon: category_security.png
  name: Sicurezza
Sports & Health:
  name: Sport e salute
System:
  icon: category_system.png
  name: Sistema
Theming:
  icon: category_theming.png
  name: Tematizzazione
Time:
  name: Tempo
Writing:
  icon: category_writing.png
  name: Scrittura
