Ads:
  name: Reklamy
  description: Tato aplikace obsahuje reklamu
DisabledAlgorithm:
  name: Podepsáno pomocí nebezpečného algoritmu
  description: Tato aplikace má slabý bezpečnostní podpis
KnownVuln:
  name: Známá zranitelnost
  description: Tato aplikace má známou zranitelnost v zabezpečení
NSFW:
  name: NSFW
  description: Tato aplikace obsahuje obsah, který by neměl bý publikovaný či viditelný
    kdekoli
NoSourceSince:
  name: Zdrojový kód už není k dispozici, aktualizace nejsou možné.
NonFreeAdd:
  name: Nesvobodné doplňky
  description: Tato aplikace propaguje nesvobodné doplňky
NonFreeAssets:
  name: Nesvobodná aktiva
  description: Tato aplikace obsahuje nesvobodné části
NonFreeDep:
  name: Nesvobodné závislosti
  description: Tato aplikace závisí na ostatních nesvobodných aplikacích
NonFreeNet:
  name: Nesvobodné síťové služby
  description: Tato aplikace propaguje nesvobodné síťové služby
Tracking:
  name: Sledování
  description: Tato aplikace zaznamenává a hlásí vaše aktivity
UpstreamNonFree:
  name: Nesvobodný Upstream
  description: Originální zdrojový kód je částečně nesvovodný
