Connectivity:
  name: Připojení
Development:
  name: Vývoj
Games:
  name: Hry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Peníze
Multimedia:
  name: Multimédia
Navigation:
  name: Navigace
Phone_SMS:
  name: Telefon a SMS
Reading:
  name: Čtení
Science_Education:
  name: Věda a vzdělání
Security:
  name: Zabezpečení
Sports_Health:
  name: Sport a zdraví
System:
  name: Systém
Theming:
  name: Vzhledy
Time:
  name: Čas
Writing:
  name: Psaní
