Connectivity:
  icon: category_connectivity.png
  name: Spojení
Development:
  icon: category_development.png
  name: Vývoj
Games:
  icon: category_games.png
  name: Hry
Graphics:
  icon: category_graphics.png
  name: Grafika
Internet:
  icon: category_internet.png
  name: Internet
Money:
  icon: category_money.png
  name: Peníze
Multimedia:
  name: Multimédia
Navigation:
  name: Navigace
Phone & SMS:
  name: Telefon a SMS
Reading:
  icon: category_reading.png
  name: Čtení
Science & Education:
  icon: category_science_education.png
  name: Věda a vzdělání
Security:
  icon: category_security.png
  name: Zabezpečení
Sports & Health:
  name: Sport a zdraví
System:
  icon: category_system.png
  name: Systém
Theming:
  icon: category_theming.png
  name: Vzhledy
Time:
  name: Čas
Writing:
  icon: category_writing.png
  name: Psaní
