archive:
  description: Archiv oficiálního repozitáře svobodného softwaru F-Droid. Aplikace zde jsou zastaralé a mohou obsahovat známé zranitelnosti a bezpečnostní problémy!
  icon: fdroid-icon.png
  name: Archiv F-Droid
repo:
  description: Oficiální repozitář svobodného softwaru F-Droid. Vše v tomto repozitáři je vždy sestaveno ze zdrojového kódu.
  icon: fdroid-icon.png
  name: F-Droid
